= AMCache hive file (AMCache.hve) format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

The AMCache hive file is used to store Windows diagnostic data.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the AMCache file (AMCache.hve) format
| Classification: | Public
| Keywords: | AMCache, AMCache.hve
|===

[preface]
== License

....
Copyright (C) 2020, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | February 2020 | Initial version.
| 0.0.2 | J.B. Metz | December 2020 | Additional information.
|===

:numbered:
== Overview

The AMCache hive file is used to store Windows diagnostic data. It has been
observed on Windows 7 or Server 2008 R2 and later.

The AMCache hive file can be found in:

....
C:\Windows\AppCompat\Programs\Amcache.hve
....

The AMCache is stored in a Windows NT Registry File (REGF) format.

=== Test version

Files created by the following version of programs were used to test the
information within this document:

* Windows 7
* Windows 8
* Windows 8.1
* Windows 2008 Server R2
* Windows 10 (1511, 1607, 1703, 1709, 1803, 1809, 1903, 1909, 2004, 20H2)

== Root-key

Windows version | Root-key name
--- | ---
8, 8.1, 10 | {11517B7C-E79D-4e20-961B-75A811715ADD}
10 (1511) | {356c48f6-2fee-e7ef-2a64-39f59ec3be22}

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| Root | Sub key named "Root"
|===

Values:

[cols="1,5",options="header"]
|===
| Value | Data type | Description
| CreatingCommand | REG_SZ |
| CreatingModule | REG_SZ |
|===

== Key named Root

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| Device | First seen in Windows 10 1511, last seen in Windows 10 1703
| DeviceCensus | First seen in Windows 10 1607
| DriverPackageExtended | First seen in Windows 10 1703
| File |
| Generic |
| HwItem | First seen in Windows 10 1511
| InventoryApplication | First seen in Windows 10 1607
| InventoryApplicationAppV | First seen in Windows 10 1803
| InventoryApplicationDriver |
| InventoryApplicationFile | First seen in Windows 10 1709
| InventoryApplicationFramework | First seen in Windows 10 1709
| InventoryApplicationShortcut | First seen in Windows 10 1709
| InventoryDeviceContainer | First seen in Windows 10 1607
| InventoryDeviceInterface | First seen in Windows 10 1703
| InventoryDeviceMediaClass | First seen in Windows 10 1607
| InventoryDevicePnp | First seen in Windows 10 1607
| InventoryDeviceUsbHubClass | First seen in Windows 10 1709
| InventoryDriverBinary | First seen in Windows 10 1607
| InventoryDriverPackage | First seen in Windows 10 1607
| InventoryMiscellaneousUUPInfo | First seen in Windows 10 1803
| Metadata | First seen in Windows 10 1511
| Orphan |
| Programs |
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| Sync | REG_QWORD_LITTLE_ENDIAN | Synchronization date and time +
Contains a FILETIME
|===

== DeviceCensus key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| App |
| Battery |
| Camera |
| Enterprise |
| Firmware |
| Flighting |
| Hardware |
| Location |
| Memory |
| Network |
| OS |
| Processor |
| Security | First seen in Windows 10 1709
| Speech | First seen in Windows 10 1703
| Storage |
| VM |
| WU |
| Xbox |
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| WritePermissionsCheck | REG_DWORD_LITTLE_ENDIAN |
|===

=== App sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| CensusVersion | REG_BINARY |
| IEVersion | REG_SZ |
|===

=== Battery sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| InternalBatteryCapablities | REG_BINARY |
| InternalBatteryCapacityCurrent | REG_BINARY |
| InternalBatteryCapacityDesign | REG_BINARY |
| InternalBatteryNumberOfCharges | REG_BINARY |
| IsAlwaysOnAlwaysConnectedCapable | REG_BINARY |
|===

=== Camera sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| FrontFacingCameraResolution | |
| RearFacingCameraResolution | |
|===

=== Enterprise sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| AADDeviceId | REG_SZ |
| AzureOSIDPresent | REG_BINARY |
| AzureVMType | REG_SZ |
| CDJType | REG_DWORD_LITTLE_ENDIAN |
| CommercialId | REG_SZ |
| ContainerType | REG_DWORD_LITTLE_ENDIAN |
| EnrollmentType | REG_DWORD_LITTLE_ENDIAN |
| HashedDomain | REG_SZ |
| IsCloudDomainJoined | REG_SZ |
| IsDERequirementMet | REG_SZ |
| IsDeviceProtected | REG_SZ |
| IsDomainJoined | |
| IsEDPEnabled | REG_SZ |
| IsMDMEnrolled | REG_SZ |
| MPNId | REG_SZ |
| SCCMClientId | REG_SZ |
| ServerFeatures | REG_SZ |
| SystemCenterID | REG_SZ |
|===

=== Firmware sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| FirmwareManufacturer | REG_SZ |
| FirmwareReleaseDate | REG_SZ |
| FirmwareType | REG_BINARY |
| FirmwareVersion | REG_SZ |
|===

=== Flighting sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| DeviceSampleRate | REG_BINARY |
| DriverTargetRing | REG_SZ |
| EnablePreviewBuilds | REG_BINARY |
| FlightIds | REG_SZ |
| FlightingBranchName | REG_SZ |
| IsFlightsDisabled | REG_BINARY |
| MSA_Accounts | REG_SZ |
| SSRK | REG_SZ |
|===

=== Hardware sub key

Values:

....
ChassisType
ComputerHardwareID
DeviceColor
DeviceForm
DeviceName
DigitizerSupport
DUID
InventoryId
OEMDigitalMarkerFileName
OEMManufacturerName
OEMModelBaseBoard
OEMModelName
OEMModelNumber
OEMModelSKU
OEMModelSystemFamily
OEMOptionalIdentifier
OEMSerialNumber
PhoneManufacturer
PowerPlatformRole
SoCName
StudyID
TelemetryLevel
TelemetrySettingAuthority
TPMVersion
VoiceSupported
....

=== Location sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ActivationLocationConsent | |
| ActivationLocationLat | |
| ActivationLocationLong | |
| ActivationLocationRad | |
|===

=== Memory sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| TotalPhysicalRAM | |
| TotalVisibleMemory | |
|===

=== Network sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| IMEI0 | |
| IMEI1 | |
| MCC0 | |
| MCC1 | |
| MEID | |
| MNC0 | |
| MNC1 | |
| MobileOperatorBilling | |
| MobileOperatorCommercialized | |
| MobileOperatorNetwork0 | |
| MobileOperatorNetwork1 | |
| NetworkCost | |
| SPN0 | |
| SPN1 | |
|===

=== OS sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ActivationChannel | |
| CompactOS | |
| GenuineState | |
| InstallationType | |
| InstallLanguage | |
| IsDeviceRetailDemo | |
| IsEduData | |
| IsPortableOperatingSystem | |
| IsSecureBootEnabled | |
| LanguagePacks | |
| LicenseStateReason | |
| OA3xOriginalProductKey | |
| OSEdition | |
| OSInstallType | |
| OSOOBEDateTime | REG_SZ | +
Contains a date and time string in the format: "2020-07-04T14:45:53.190"
| OSSKU | |
| OSSubscriptionStatus | |
| OSSubscriptionTypeId | |
| OSTimeZoneBiasInMins | |
| OSUILocale | |
| ProductActivationResult | |
| ProductActivationTime | REG_QWORD_LITTLE_ENDIAN | Product activiation date and time +
Contains a FILETIME
| ProductKeyID2 | |
| RACw7Id | |
| ServiceMachineIP | |
| ServiceMachinePort | |
| ServiceProductKeyID | |
| SharedPCMode | |
| Signature | |
| SLICStatus | |
| SLICVersion | |
|===

=== Processor sub key

Values:

....
ProcessorArchitecture
ProcessorClockSpeed
ProcessorCores
ProcessorManufacturer
ProcessorModel
ProcessorPhysicalCores
SocketCount
....

=== Storage sub key

Values:

....
PrimaryDiskTotalCapacity
PrimaryDiskType
SystemVolumeTotalCapacity
....

=== VM sub key

Values:

....
HyperVisor
IOMMUPresent
IsVirtualDevice
SLATSupported
VirtualizationFirmwareEnabled
....

=== WU sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| OSAssessmentReleaseInfoTime | REG_SZ | +
Contains a date and time string in the format: "2020-07-04T14:45:53.190"
|===

....
AppraiserGatedStatus
AppStoreAutoUpdate
AppStoreAutoUpdateMDM
AppStoreAutoUpdatePolicy
DelayUpgrade
OSRollbackCount
OSRolledBack
OSUninstalled
OSWUAutoUpdateOptions
UninstallActive
UpdateServiceURLConfigured
WUDeferUpdatePeriod
WUDeferUpgradePeriod
WUDODownloadMode
WUMachineId
WUPauseState
WUServer
....

=== Xbox sub key

Values:

....
XboxConsolePreferredLanguage
XboxConsoleSerialNumber
XboxLiveDeviceId
XboxLiveSandboxId
....

== DriverPackageExtended key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderVersion | |
|===

== File key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| %GUID% | Volume identifier
|===

=== Volume sub key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| %ID% | File system file reference +
Where for NTFS the separator between the MFT entry and sequence number is "0000" e.g. "100001605a" on NTFS represents MFT entry 90202 (0x1605a) and with sequence number 1 or in shorthand 90202-1
|===

[NOTE]
The file reference is dependent on file system, e.g. for a removable media
presumably FAT "019c"

==== File sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| 0 | REG_SZ | Product name
| 1 | REG_SZ | Company name
| 2 | REG_SZ | [yellow-background]*PE/COFF file or product version ?* +
This corresponds with the file or product version in the PE/COFF file version information
| 3 | REG_DWORD_LITTLE_ENDIAN | Language code +
Contains a LCID
| 4 | REG_QWORD_LITTLE_ENDIAN | [yellow-background]*Unknown (SwitchBackContext)?*
| 5 | REG_SZ | [yellow-background]*PE/COFF file or product version ?* +
This corresponds with the file or product version in the PE/COFF file version information
| 6 | REG_DWORD_LITTLE_ENDIAN | File size
| 7 | REG_QWORD_LITTLE_ENDIAN | PE/COFF image size +
This corresponds with the image size value in the PE/COFF PE/COFF header
| 8 | REG_SZ | [yellow-background]*Hash of PE Header?*
| 9 | REG_DWORD_LITTLE_ENDIAN | PE/COFF checksum (or hash) +
This corresponds with the checksum value in the PE/COFF PE/COFF header
| a | REG_DWORD_LITTLE_ENDIAN | [yellow-background]*Unknown?*
| b | REG_DWORD_LITTLE_ENDIAN | [yellow-background]*Unknown?*
| c | REG_SZ | PE/COFF description +
This corresponds with the FileDescription value in the PE/COFF file version information
| d | REG_DWORD_LITTLE_ENDIAN | PE/COFF image version +
This corresponds with the MajorImageVersion and MinorImageVersion values in the PE/COFF PE/COFF header
3+|
| f | REG_DWORD_LITTLE_ENDIAN | Compilation (or Link) date and time +
This corresponds with the creation time in the PE/COFF header +
Contains a POSIX timestamp in seconds
| 10 | REG_DWORD_LITTLE_ENDIAN | [yellow-background]*Unknown (major operating system version)?* +
Seen: 6
| 11 | REG_QWORD_LITTLE_ENDIAN | File modification date and time +
For NTFS this corresponds with the modification time in the $STANDARD_INFORMATION attribute +
Contains a FILETIME
| 12 | REG_QWORD_LITTLE_ENDIAN | File creation date and time +
For NTFS this corresponds with the creation time in the $STANDARD_INFORMATION attribute +
Contains a FILETIME
3+|
| 15 | REG_SZ | Path
| 16 | REG_DWORD_LITTLE_ENDIAN | [yellow-background]*Unknown?* +
Seen: 0 (PE/COFF information is also present), 1
| 17 | REG_QWORD_LITTLE_ENDIAN | [yellow-background]*AEINV_WER modification date and time?* +
Contains a FILETIME
3+|
| 100 | REG_SZ | Program identifier (ProgramId)
| 101 | REG_SZ | SHA-1 of the excutable file +
The string consists of 4 leading zeros followed by a SHA-1
|===

== InventoryApplication key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| %ID% | Program identifier (ProgramId)
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| LastScanTime | REG_QWORD_LITTLE_ENDIAN |  +
Contains a FILETIME
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider +
Seen: "{1b5a86a8-5f1b-4032-8592-32113f1174e1}", "{0b4fdded-d2c2-4e11-b0b2-579bd34983ea}"
| WritePermissionsCheck | REG_DWORD | +
Seen: 1
|===

=== Application sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| HiddenArp | |
| InboxModernApp | |
| InstallDate | | Installation date and time +
Contains a locale specific date and time value e.g. "07/16/2016 22:55:48"
| InstallDateArpLastModified | REG_MULTI_SZ | +
Seen: ["08/01/2017 13:14:28"]
| InstallDateFromLinkFile | |
| InstallDateMsi | REG_SZ | MSI installation date and time +
Contains a locale specific date and time value e.g. "08/01/2017 13:08:04"
| Language | REG_SZ | Language code +
Contains a LCID or "0" if not set
| MsiPackageCode | REG_SZ | +
Contains "{%GUID%}" or empty if not set
| MsiProductCode | REG_SZ | +
Contains "{%GUID%}" or empty if not set
| Name | REG_SZ |
| OSVersionAtInstallTime | REG_SZ | Windows version at the time of installation +
E.g. "10.0.0.14393"
| PackageFullName | REG_SZ |
| ProgramId | REG_SZ | Program identifier (ProgramId)
| ProgramInstanceId | REG_SZ | Program instance identifier (ProgramId)
| Publisher | REG_SZ |
| RegistryKeyPath | REG_SZ |
| RootDirPath | REG_SZ |
| Source | REG_SZ | +
Seen: "AppxPackage", "AddRemoveProgram", "Msi", "File"
| UninstallString | REG_SZ |
| Version | REG_SZ |
|===

== InventoryApplicationAppV key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| WritePermissionsCheck | |
|===

== InventoryApplicationDriver key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| WritePermissionsCheck | |
|===

== InventoryApplicationFile key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| `%NAME%|%IDENTIFIER%` +
`0000%SHA1%` | Application
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| WritePermissionsCheck | |
|===

=== Application sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| BinaryType | |
| BinFileVersion | |
| BinProductVersion | |
| FileId | |
| IsOsComponent | |
| IsPeFile | |
| Language | |
| LinkDate | |
| LongPathHash | |
| LowerCaseLongPath | |
| Name | |
| ProductName | |
| ProductVersion | |
| ProgramId | | Program identifier (ProgramId)
| Publisher | |
| Size | |
| Usn | |
| Version | |
|===

== InventoryApplicationFramework key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| WritePermissionsCheck | |
|===

== InventoryApplicationShortcut key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| WritePermissionsCheck | |
|===

== InventoryDeviceContainer key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| `%GUID%` |
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| ProviderVersion | |
|===

=== GUID sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| Categories | |
| DiscoveryMethod | |
| FriendlyName | |
| Icon | |
| IsActive | |
| IsConnected | |
| IsMachineContainer | |
| IsNetworked | |
| IsPaired | |
| Manufacturer | |
| ModelId | |
| ModelName | |
| ModelNumber | |
| PrimaryCategory | |
| State | |
|===

== InventoryDeviceInterface key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| DeviceInterfaces | First seen in Windows 10 1703
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| ProviderVersion | |
|===

=== DeviceInterfaces sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| Accelerometer3D | |
| ActivityDetection | |
| AmbientLight | |
| Barometer | |
| Custom | |
| EnergyMeter | |
| FloorElevation | |
| GeomagneticOrientation | |
| GravityVector | |
| Gyrometer3D | |
| Humidity | |
| LinearAccelerometer | |
| Magnetometer3D | |
| Orientation | |
| Pedometer | |
| Proximity | |
| RelativeOrientation | |
| SimpleDeviceOrientation | |
| Temperature | |
|===

== InventoryDeviceMediaClass key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| [yellow-background]*some identifier* |
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| ProviderVersion | |
|===

=== Sub key

[yellow-background]*TODO: describe*

== InventoryDevicePnp key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| [yellow-background]*some identifier* |
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| ProviderVersion | |
|===

=== Sub key

[yellow-background]*TODO: describe*

== InventoryDeviceUsbHubClass key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| DeviceUsbHubClass |
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| ProviderVersion | |
|===

=== DeviceUsbHubClass sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| TotalUserConnectablePorts | |
| TotalUserConnectableTypeCPorts | |
|===

== InventoryDriverBinary key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| ProviderVersion | |
|===

== InventoryDriverPackage key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| ProviderVersion | |
|===

== InventoryMiscellaneousUUPInfo key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| [yellow-background]*some identifier* |
|===

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| ProviderSyncId | REG_SZ | Provider identifier +
Contains a GUID of the provider
| WritePermissionsCheck | |
|===

=== Sub key

[yellow-background]*TODO: describe*

== Programs key

Sub keys:

[cols="1,5",options="header"]
|===
| Name | Description
| %ID% | Program identifier (ProgramId)
|===

=== Program sub key

Values:

[cols="1,1,5",options="header"]
|===
| Value | Data type | Description
| 0 | REG_SZ | Name
| 1 | REG_SZ | Version
| 2 | REG_SZ | Publisher
| 3 | REG_SZ | Language code +
Contains a LCID or an empty string or "0" if not set
3+|
| 5 | REG_DWORD | [yellow-background]*Unknown?* +
Seen: 1
| 6 | REG_SZ | Installation method (or source) +
Seen: "AddRemoveProgram", "AddRemoveProgramPerUser", "Msi"
| 7 | REG_MULTI_SZ | Uninstallation Registry key path(s)
3+|
| a | REG_QWORD | Installation date and time +
Contains a POSIX timestamp in seconds
| b | REG_QWORD | Uninstallation date and time +
Contains a POSIX timestamp in seconds or 0 if program has not been uninstalled
3+|
| d | REG_MULTI_SZ | Installation directories (or DirectoryIndicators)
3+|
| f | REG_SZ | [yellow-background]*Unknown (Product Code)?*
| 10 | REG_SZ | [yellow-background]*Unknown (Package Code)?*
| 11 | REG_MULTI_SZ | [yellow-background]*Unknown (MSI Product Code)?*
| 12 | REG_MULTI_SZ | [yellow-background]*Unknown (MSI Package Code)?*
| 13 | REG_DWORD | [yellow-background]*Unknown?* +
Seen: 0
| 14 | REG_DWORD |
| 15 | REG_DWORD |
| 16 | REG_BINARY |
| 17 | REG_QWORD | [yellow-background]*Unknown (uninstall key)?*
| 18 | REG_DWORD |
3+|
| Files | REG_MULTI_SZ | Identifiers of the corresponding file reference keys under the "\Root\File" key +
Contains "%VOLUME_GUID%@%FILE_REFERENCE%
|===

:numbered!:
[appendix]
== References

`[REFERENCE]`

[cols="1,5",options="header"]
|===
| Title: |
| Author(s): |
| Date: |
| URL: |
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

