= Apple Spotlight store file formats

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

The Apple Spotlight store file formats are used by MacOS and iOS to store
the Spotlight desktop search information. This specification is based
on available source code and documentation.

This document is intended as a working document for the Apple Spotlight
store file formats specification.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | Apple Spotlight store file formats
| Classification: | Public
| Keywords: | Apple Spotlight store, store.db
|===

[preface]
== License

....
Copyright (C) 2020-2023, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | June 2020 | Initial version based on earlier notes, with thanks to Everest Munro-Zeisberger
| 0.0.2 | J.B. Metz | June 2023 | Additional changes based on format analysis
|===

:numbered:
== Overview

The Apple Spotlight store file formats are used by MacOS and iOS to store
the Spotlight desktop search information. This specification is based on
available source code and documentation.

The Spotlight store is typically stored under:

....
/.Spotlight-V100/Store-V2/${UUID}/
....

But can also be stored in other locations such as:

....
/private/var/db/Spotlight-V100/BootVolume/Store-V2/${UUID}/
/Users/${USERNAME}/Library/Caches/com.apple.helpd/index.spotlightV3/
/Users/${USERNAME}/Library/Metadata/CoreSpotlight/index.spotlightV3/
/Users/${USERNAME}/Library/Developer/Xcode/DocumentationCache/v18/9.0.1/DeveloperDocumentation.index/
....

The Spotlight store consists of the following files:

* .store.db
* store.db

In macOS 10.15 (Catalina) the following <<database_streams_map_files,database streams map files>>
were added:

* dbStr-#.map.buckets
* dbStr-#.map.data
* dbStr-#.map.header
* dbStr-#.map.offsets

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | Cocoa and POSIX date and time values
| Character strings | UTF-8 formatted strings
|===

=== Test versions

The following version of programs were used to test the information within this
document:

* Mac OS X 10.7 (Lion)
* Mac OS X 10.8 (Mountain Lion)
* Mac OS X 10.9 (Mavericks)
* Mac OS X 10.10 (Yosemite)
* Mac OS X 10.11 (El Capitan)
* macOS 10.12 (Sierra)
* macOS 10.13 (High Sierra)
* macOS 10.14 (Mojave)
* macOS 10.15 (Catalina)
* macOS 11 (Big Sur)
* macOS 12 (Monterey)
* macOS 13 (Ventura)

== Store database file

A store database (store.db) file consists of:

* file header
* map
* property tables
  * metadata attribute types
  * metadata attribute values
  * data records

=== File header

The file header is at least 720 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "8tsd" | Signature
| 4 | 4 | | Flags +
See section: <<file_header_flags,File header flags>>
| 8 | 4 | | [yellow-background]*Unknown (0-byte values)*
| 12 | 4 | | [yellow-background]*Unknown* +
Seen: 0x0c
| 16 | 4 | | [yellow-background]*Unknown (0-byte values)*
| 20 | 4 | | [yellow-background]*Unknown*
| 24 | 4 | | [yellow-background]*Unknown (0-byte values)*
| 28 | 4 | | [yellow-background]*Unknown*
| 32 | 4 | | [yellow-background]*Unknown (0-byte values)*
| 36 | 4 | | Map offset
| 40 | 4 | | Map size
| 44 | 4 | | Page size
| 48 | 4 | | Metadata attribute types (property table) block number
| 52 | 4 | | Metadata attribute values (property table) block number
| 56 | 4 | | [yellow-background]*Unknown* (property table) block number
| 60 | 4 | | Metadata attribute lists (property table) block number
| 64 | 4 | | Metadata attribute localized strings (property table) block number
| 68 | 256 | | [yellow-background]*Unknown*
| 324 | 256 | | Path
| 580 | 140 | | [yellow-background]*Unknown*
|===

The file header is stored in the first 4096 bytes

[NOTE]
The signature is "dst8" in little-endian, which cloud represention something
in line of "data store".

==== [[file_header_flags]]File header flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | | Seen in .store.db and store.db
| | |
| 0x00000004 | | Seen in .store.db and store.db
| 0x00000008 | | Seen in .store.db
| | |
| 0x00000100 | | Seen in .store.db and store.db
| | |
| 0x00000400 | | Seen in .store.db
| 0x00000800 | | Seen in .store.db and store.db
| | |
| 0x00010000 | | [yellow-background]*Unknown (Has database streams map files)?*
|===

=== Pages

....
file offset = block number x 0x1000
....

=== Map
==== Map page header

The map page header is 20 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "1mdb" +
"2mbd" | Signature
| 4 | 4 | | Page size
| 8 | 4 | | Number of map values
| 12 | 4 | | [yellow-background]*Unknown*
| 16 | 4 | | [yellow-background]*Unknown (type?)*
|===

[NOTE]
The signature is "dbm1" or "dbm2" in little-endian, which cloud represention
something in line of "database map".

==== Map page value

The map page value is 16 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | [yellow-background]*Unknown*
| 8 | 4 | | Data record block number
| 12 | 4 | | [yellow-background]*Unknown (page size and flags?)*
|===

....
00001010              ab d5 00 00  00 00 00 00 19 00 00 00  |................|
00001020  00 40 00 00                                       |.@..,d......Y...|

00001020              2c 64 01 00  00 00 00 00 59 00 00 00  |.@..,d......Y...|
00001030  00 40 00 00 9c be 01 00  00 00 00 00 59 01 00 00  |.@..........Y...|
00001040  00 40 00 00 62 ca 01 00  00 00 00 00 55 00 00 00  |.@..b.......U...|
00001050  00 40 00 00 0e d2 01 00  00 00 00 00 51 00 00 00  |.@..........Q...|
....

[yellow-background]*TODO what about "1mbd"*

=== Property table

==== Property table page header

The property table page header is 20 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "2pbd" | Signature
| 4 | 4 | | Page size
| 8 | 4 | | Used page size +
Contains the size of the space in the page that is in use, which includes this header
| 12 | 4 | | Property table type [yellow-background]*(or flags?)* +
See section: <<property_table_types,Property table types>>
| 16 | 4 | | Uncompressed page size +
Contains the size of the uncompressed page, which includes this header, or 0 if the page is not compressed
|===

[NOTE]
The signature is "dbp2" in little-endian, which cloud represention something
in line of "database property".

==== [[property_table_types]]Property table types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000009 | | data records +
Page contains zlib+DEFLATE compressed data
| 0x00000011 | | Metadata attribute types +
Page contains a <<property_table_header,property table header>>
| 0x00000021 | | Metadata attribute values +
Page contains a <<property_table_header,property table header>>
| 0x00000041 | | [yellow-background]*Unknown* +
Page contains a <<property_table_header,property table header>>
| 0x00000081 | | Metadata lists or localized strings +
Page contains a <<property_table_header,property table header>>
3+| _Flags_
| 0x00001000 | | Data is LZ4 compressed
| 0x00004000 | | [yellow-background]*Unknown*
|===

==== Compressed data

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| "\x78" | | start of zlib+DEFLATE compressed data
| "bv41" | | LZ4 compressed block marker +
See section: <<lz4_compressed_block,LZ4 compressed block>>
| "bv4-" | | LZ4 uncompressed block marker +
See section: <<lz4_uncompressed_block,LZ4 uncompressed block>>
| "bv4$" | | end of LZ4 compressed stream marker
|===

==== [[lz4_compressed_block]]LZ4 compressed block

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _LZ4 compressed block header_
| 0 | 4 | "bv41" | LZ4 compressed block marker
| 4 | 4 | | Uncompressed data size (in bytes)
| 8 | 4 | | LZ4 compressed data size (in bytes)
4+| _LZ4 compressed block data_
| 12 | ... | | LZ4 compressed data
|===

==== [[lz4_uncompressed_block]]LZ4 uncompressed block

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "bv4-" | LZ4 uncompressed block marker
| 4 | 4 | | Uncompressed data size (in bytes)
4+| _LZ4 uncompressed block data_
| 8 | ... | | Uncompressed data
|===

==== [[property_table_header]]Property table header

The property table header is 12 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Next block offset +
Contains the offset of the next property table page relative to the start of the file or 0 if not set
| 4 | 8 | | [yellow-background]*Unknown (checksum?)*
|===

==== Data record (type 0x09)

The data record (type 0x09) is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Record data size
4+| _Record data_
| 4 | ... | | Identifier +
A variable size integer that contains the file system identifier, e.g. CNID on HFS, of the corresponding file (system) entry
| ... | 1 | | Data record flags +
See section: <<data_record_flags,Data record flags>>
| ... | ... | | Item identifier +
Contains a variable size integer
| ... | ... | | Parent identifier +
A variable size integer that contains the file system identifier, e.g. CNID on HFS, of the parent file (system) entry
| ... | ... | | Last updated time +
Contains a variable size integer that contains the number of microseconds since January 1, 1970 00:00:00 +
[yellow-background]*Assuming this is UTC*
| ... | ... | | Properties array
|===

==== [[data_record_flags]]Data record flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x01 | | [yellow-background]*Unknown (Is metadata?)* +
Seen in record with identifier 0
| 0x02 | |
3+|
| 0x10 | |
| 0x20 | |
| 0x40 | |
|===

[yellow-background]*TODO: describe property*

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | Property data size +
Contains a variable size integer
|===

==== Metadata attribute types property table (type 0x11) value

The metadata attribute types property table (type 0x11) value is variable of
size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Table index
| 4 | 1 | | Value type +
See section: <<metadata_attribute_value_types,Metadata attribute value types>>
| 5 | 1 | | Property type
| 6 | ... | | Key name +
Contains an UTF-8 encoded string with an end-of-string character
|===

==== Metadata attribute values property table (type 0x21) value

The metadata attribute values property table (type 0x21) value is variable of
size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Table index
| 4 | ... | | Metadata attribute value name +
Contains an UTF-8 encoded string with an end-of-string character
|===

[NOTE]
Some value names contain "\x16\x02" (SYN, STX), followed by a language
identifier.

==== Unknown property table (type 0x41) value

....
0x00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
...
0x00003fd0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
....

==== Metadata lists or localized strings property table (type 0x81) value

The metadata lists or localized strings property table (type 0x81) value is
variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Table index
| 4 | ... | | Index data size +
Contains a variable size integer
4+| __Index data__
| ... | ... | | [yellow-background]*Unknown (Index data padding?)* +
If the index data size is not a multitude of 4 (32-bit) additional bytes are stored before the index array
| ... | ... | | Index array +
Contains an array of 32-bit integer values
|===

=== Metadata attributes

The metadata attributes are stored using several property tables.

* The metadata attribute types table, contain the key names, value types and property types of the metadata attributes
* The metadata attribute values table, contains the values used by the metadata attributes
* The metadata attribute lists table, contains the lists of values used by the metadata attributes
* The metadata attribute localized string table, contains the lists of localized string values used by the metadata attributes

==== [[metadata_attribute_value_types]]Metadata attribute value types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00 | | Boolean +
Contains a variable size integer +
See section: <<variable_size_integer,Variable size integer>> +
| 0x01 | | [yellow-background]*Unknown*
| 0x02 | | [yellow-background]*Unknown* +
Contains a variable size integer +
See section: <<variable_size_integer,Variable size integer>> +
Seen in combination with "_kMDItemGroupId"
| 0x03 | | [yellow-background]*Unknown*
| 0x04 | | [yellow-background]*Unknown*
| 0x05 | | [yellow-background]*Unknown*
| 0x06 | | [yellow-background]*Unknown* +
Contains a variable size integer +
See section: <<variable_size_integer,Variable size integer>> +
Seen in combination with "_kStoreMetadataVersion"
| 0x07 | | Variable size integer +
See section: <<variable_size_integer,Variable size integer>> +
If the 2nd LSB of the property type is set the value data contains a multi-value. See section <<multi_value,Multi-value>>
| 0x08 | | [yellow-background]*Unknown (Byte or 8-bit integer)*
| 0x09 | | Floating-point 32-bit +
If the 2nd LSB of the property type is set the value data contains a multi-value. See section <<multi_value,Multi-value>>
| 0x0a | | Floating-point 64-bit +
If the 2nd LSB of the property type is set the value data contains a multi-value. See section <<multi_value,Multi-value>>
| 0x0b | | String +
Contains strings data +
See section: <<strings_data,Strings data>> +
[yellow-background]*The 2 LSB of the property type indicate if the value is a list of localized strings (0x3), list of strings (0x2) or single string (0x1, 0x0)*
| 0x0c | | Date and time +
Contains a floating-point 64-bit values of a Cocoa timestamp +
If the 2nd LSB of the property type is set the value data contains a multi-value. See section <<multi_value,Multi-value>>
| 0x0e | | Binary data +
See section: <<binary_data,Binary data>>
| 0x0f | | Metadata attribute value or list reference +
[yellow-background]*The 2 LSB of the property type indicate if the value references a localized string (0x3), list (0x2) or value (0x1) type*
|===

==== [[variable_size_integer]]Variable size integer

==== [[multi_value]]Multi-value

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | Values data size +
Contains a variable size integer
| ... | ... | | Values data +
Contains data dependent on the value type
|===

==== [[strings_data]]Strings data

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | Strings data size +
Contains a variable size integer
| ... | ... | | Strings data +
Contains one or more UTF-8 encoded strings with an end-of-string character
|===

==== [[binary_data]]Binary data

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | Binary data size +
Contains a variable size integer
| ... | ... | | Binary data
|===

=== Metadata item (MDItem)

==== Metadata item 0x01

Metadata attributes:

[cols="1,1,1,5",options="header"]
|===
| Value | Property type | Value type | Description
| `_kStoreMetadataVersion` | 0x0c | 0x06 | Contains a 32-bit integer with version information where the upper 16-bit contains the major version and the lower 16-bit the minor version, for example 0x0001000d represents "1.13"
| kMDStoreProperties | 0x0c | 0x0e | Contains a XML plist
| kMDStoreUUID | 0x0c | 0x0e | Contains the store UUID +
[yellow-background]*Is the UUID stored in big-endian?*
| kMDStoreAccumulatedSizes | 0x0e | 0x08 | [yellow-background]*Unknown, does not follow the normal behavior of value type 0x08, could this be due to flags 0x01?*
|===

....
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CabGroupsConverted</key>
        <string>23</string>
        <key>MLMailFlagsFixUp</key>
        <string>14F27</string>
        <key>MLMailReadFixUp</key>
        <string>14F27</string>
        <key>MLReimportedApps</key>
        <true/>
        <key>MLReimportedChats</key>
        <true/>
        <key>MLReimportedFailures</key>
        <string>14F27</string>
        <key>MLReimportedMail</key>
        <true/>
        <key>ReimportedAltNames</key>
        <string>14F27</string>
        <key>ReimportedPhotoLibraries</key>
        <true/>
        <key>SDBConsistencyCheck</key>
        <string>14F27</string>
        <key>database.diskstoreversion</key>
        <integer>2</integer>
        <key>database.fseventsuuid</key>
        <string>B3F639AD-3C93-4970-9D7E-EAD2B0875FDA</string>
        <key>database.fullyindexbysnowleopard</key>
        <true/>
        <key>database.localizedtermsuuid</key>
        <data>
        9RsNbp5KQI+fBJGSuOkzSQ==
        </data>
        <key>database.recoverscantime</key>
        <integer>1442686011</integer>
        <key>database.shutdowntime</key>
        <integer>1440532242</integer>
        <key>database.volumeuuid</key>
        <string>8C76D365-800A-3B5C-8320-55C3E6032D70</string>
        <key>kCabReimportedMail</key>
        <true/>
        <key>kIndexCheckDupOids</key>
        <string>14F27</string>
        <key>kIndexRemappingData</key>
        <key>kIndexRemappingData</key>
        <dict>
                <key>kIndexRemappingIndex</key>
                <integer>4</integer>
                <key>kIndexRemappings</key>
                <array/>
        </dict>
        <key>kMDSIndexSyncCount</key>
        <integer>41</integer>
        <key>kSIConsistencyCheck</key>
        <string>14F27</string>
        <key>kSIRepairSizes</key>
        <string>14F27</string>
        <key>kSIRepairedIndex</key>
        <true/>
        <key>scan.fullscancomplete</key>
        <true/>
        <key>scan.fullscanrequesttime</key>
        <integer>1435155044</integer>
        <key>scan.scancompletetime</key>
        <integer>1435157167</integer>
</dict>
</plist>
....

....
Metadata attribute: 3 type index                                        : 21
Key name                                                                : kMDStoreAccumulatedSizes
Property type                                                           : 0x0e
Value type                                                              : 0x08
Data:
0x00000000  80 98 00 e0 30 a2 44 c0  50 00 f0 25 18 20 00 f0  ....0.D.P..%. ..
0x00000010  3b ae 04 e0 d9 c0 00 83  1b e2 ca d0 00 f3 66 f6  ;.............f.
0x00000020  40 00 00 e3 a6 9e 00 e2  22 91 28 c0 5e 74 f0 37  @.......".(.^t.7
0x00000030  e5 a8 81 e4 7a 42 c3 f0  38 6f 18 7e a2 00 00 f0  ....zB..8o.~....

Metadata attribute: 3 type index                                        : 67
Key name                                                                : kMDStoreAccumulatedSizes
Property type                                                           : 0x0e
Value type                                                              : 0x08
Data:
0x00000000  80 98 00 00 a0 00 e5 67  20 00 f0 1f 9d 11 44 00  .......g .....D.
0x00000010  83 1b f0 12 5a c0 00 f0  ae f4 31 6d 00 f0 52 fc  ....Z.....1m..R.
0x00000020  0a 60 e3 8d df 39 c1 07  3a f0 45 57 00 f8 ea 2f  .`...9..:.EW.../
0x00000030  23 54 f0 81 cc d2 e2 a2  00 00 f8 0a              #T..........

Relative metadata attribute: 3 type index                               : 1
Metadata attribute: 3 type index                                        : 23
Key name                                                                : kMDStoreAccumulatedSizes
Property type                                                           : 0x0e
Value type                                                              : 0x08
Data:
0x00000000  80 88 00 00 00 00 00 00  00 00 00 00 00 00 00     ...............
....

==== Metadata item

[cols="1,1,1,5",options="header"]
|===
| Value | Property type | Value type | Description
| `_kMDItemAppStoreRefID` | | |
| `_kMDItemContentChangeDate` | | 0x0c |
| `_kMDItemCreationDate` | | 0x0c | Creation date and time of [yellow-background]*the corresponding file (system) entry?*
| `_kMDItemCreatorCode` | | 0x07 |
| `_kMDItemFileName` | | 0x0b | Name of the corresponding file (system) entry
| `_kMDItemFinderExcluded` | | 0x00 |
| `_kMDItemFinderFlags` | | 0x07 |
| `_kMDItemFinderLabel` | | 0x07 |
| `_kMDItemGroupId` | | 0x02 |
| `_kMDItemImporterResult` | | |
| `_kMDItemIndexedByBackup` | | |
| `_kMDItemIsExtensionHidden` | | 0x00 |
| `_kMDItemLocked` | | |
| `_kMDItemNodeCount` | | |
| `_kMDItemOwnerGroupID` | | 0x07 |
| `_kMDItemOwnerUserID` | | 0x07 |
| `_kMDItemPrescanCandidate` | | |
| `_kMDItemSizingIsNeeded` | | |
| `_kMDItemStaticInterestScore` | | 0x09 |
| `_kMDItemTextContentIndexExists` | | |
| `_kMDItemTextEncodingHint` | | |
| `_kMDItemTimeMachinePath` | | |
| `_kMDItemTypeCode` | | 0x07 |
| `_kMDItemUpgraded` | | |
| `_kMDXXXX___DUMMY`` | | |
| `_kTimeMachineNewestSnapshot` | | 0x0c |
| `_kTimeMachineOldestSnapshot` | | 0x0c |
| com_apple_ats_name_family | | |
| com_apple_ats_name_fond | | |
| com_apple_ats_name_full | | |
| com_apple_ats_name_postscript | | |
| com_apple_ats_names | | |
| com_apple_ats_name_style | | |
| com_apple_backup_excludeItem | | |
| com_apple_iCal_Bookmark_FullDay | | |
| com_apple_iCal_Bookmark_SharedUID | | |
| com_apple_mail_attachmentKinds | | |
| com_apple_mail_attachmentNames | | |
| com_apple_mail_attachmentSpecificTypes | | |
| com_apple_mail_attachmentTypes | | |
| com_apple_mail_dateLastViewed | | |
| com_apple_mail_dateReceived | | |
| com_apple_mail_flagged | | |
| com_apple_mail_messageID | | |
| com_apple_mail_priority | | |
| com_apple_mail_read | | |
| com_apple_mail_repliedTo | | |
| com_apple_system_prefs_keywords | | |
| kMDItemAlternateNames | | |
| kMDItemAppStoreAdamID | | |
| kMDItemAppStoreCategory | | |
| kMDItemAppStoreCategoryType | | |
| kMDItemAppStoreHasReceipt | | |
| kMDItemAppStoreInstallerVersionID | | |
| kMDItemAppStoreIsAppleSigned | | |
| kMDItemAppStorePurchaseDate | | 0x0c |
| kMDItemAppStoreReceiptIsRevoked | | |
| kMDItemAppStoreReceiptIsVPPLicensed | | |
| kMDItemAppStoreReceiptType | | |
| kMDItemAttributeChangeDate | | |
| kMDItemAudioBitRate | | |
| kMDItemAudioChannelCount | | |
| kMDItemAudioSampleRate | | |
| kMDItemAuthorEmailAddresses | | |
| kMDItemAuthors | | |
| kMDItemBitsPerSample | | |
| kMDItemCFBundleIdentifier | | |
| kMDItemCity | | |
| kMDItemColorSpace | | |
| kMDItemComment | | |
| kMDItemContentCreationDate | | 0x0c |
| kMDItemContentModificationDate | | 0x0c |
| kMDItemContentType | | 0x0f | Value string
| kMDItemContentTypeTree | | 0x0f | Value list
| kMDItemCopyright | | |
| kMDItemCountry | | |
| kMDItemCoverage | | |
| kMDItemCreator | | |
| kMDItemDateAdded | | 0x09 |
| kMDItemDisplayName | | 0x0b |
| kMDItemDownloadedDate | 0x0c |
| kMDItemDurationSeconds | | |
| kMDItemEditors | | |
| kMDItemEncodingApplications | | |
| kMDItemExecutableArchitectures | | |
| kMDItemFonts | | |
| kMDItemHasAlphaChannel | | |
| kMDItemInvisibleFileType | | |
| kMDItemIsApplicationManaged | | |
| kMDItemIsLikelyJunk | | |
| kMDItemKeywords | | |
| kMDItemKind | | 0x0f | Localized string
| kMDItemLanguages | | |
| kMDItemLastUsedDate | | 0x0c |
| kMDItemLogicalSize | | 0x07 |
| kMDItemMediaTypes | | |
| kMDItemNumberOfPages | | |
| kMDItemOrientation | | |
| kMDItemPageHeight | | |
| kMDItemPageWidth | | |
| kMDItemPhoneNumbers | | |
| kMDItemPhysicalSize | | 0x07 |
| kMDItemPixelCount | | |
| kMDItemPixelHeight | | |
| kMDItemPixelWidth | | |
| kMDItemProfileName | | |
| kMDItemPublishers | | |
| kMDItemRecipientEmailAddresses | | |
| kMDItemRecipients | | |
| kMDItemResolutionHeightDPI | | |
| kMDItemResolutionWidthDPI | | |
| kMDItemSecurityMethod | | |
| kMDItemStateOrProvince | | |
| kMDItemSubject | | |
| kMDItemSupportFileType | | |
| kMDItemTitle | | |
| kMDItemTotalBitRate | | |
| kMDItemURL | | |
| kMDItemURL | | 0x0b |
| kMDItemUseCount | | |
| kMDItemUsedDates | 0x0c | Contains an array of date and time values
| kMDItemVersion | | |
| kMDItemWhereFroms | | |
|===

== [[database_streams_map_files]]Database streams map (dbStr-#.map) files

The # in the filename corresponds to the nature of the strings in the map.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 1 | | Metadata types streams map
| 2 | | Metadata values streams map
| 3 | | Unknown values 0x41 streams map
| 4 | | Metadata lists streams map
| 5 | | Metadata localized strings streams map
|===

=== Database streams map header file (dbStr-#.map.header)

The database streams map header file (dbStr-#.map.header) file is 56 bytes in
size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | "\x00PataD\x00\x00" | Signature
| 8 | 4 | | [yellow-background]*Unknown (Seen: 13)*
| 12 | 4 | | [yellow-background]*Unknown (Seen: 0, 2 in dbStr-1.map.header)*
| 16 | 4 | | [yellow-background]*Unknown (Seen: 1)*
| 20 | 4 | | Size of the data in the corresponding dbStr-#.map.data file
| 24 | 4 | | Number of entries in the corresponding dbStr-#.map.buckets file
| 28 | 4 | | Number of entries in the corresponding dbStr-#.map.ofsets file
| 32 | 4 | | [yellow-background]*Unknown (copy of value at offset 20?)*
| 36 | 4 | | [yellow-background]*Unknown (copy of value at offset 24?)*
| 40 | 4 | | [yellow-background]*Unknown (copy of value at offset 28?)*
| 44 | 4 | 0 | [yellow-background]*Unknown (empty)*
| 48 | 4 | 0 | [yellow-background]*Unknown (empty)*
| 52 | 4 | 0 | [yellow-background]*Unknown (empty)*
|===

=== Database streams map offsets file (dbStr-#.map.offsets)

The database streams map offsets file (dbStr-#.map.offsets) file is variable of
size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 x number of entries | | Array of 32-bit offsets +
The offset of the value in the corresponding dbStr-#.map.data file
| ... | ... | 0 | [yellow-background]*Unknown (empty)*
|===

The size of corresponding stream value is calculated as:

....
size = next offset or data size - current offset
....

=== Database streams map data file (dbStr-#.map.data)

The database streams map data file (dbStr-#.map.data) is variable of size and
consists of:

* One or more stream values

[NOTE]
Note that the first stream value always appears to be a single 0-byte value.

A stream value is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | Stream value data
|===

==== Metadata attribute types

The dbStr-1.map.data file contains metadata attribute types that consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | [yellow-background]*Unknown (stream value data size)* +
See section: <<variable_size_integer,Variable size integer>>
| ... | 1 | | Value type +
See section: <<metadata_attribute_value_types,Metadata attribute value types>>
| ... | 1 | | Property type
| ... | ... | | Key name +
Contains an UTF-8 encoded string with an end-of-string character
|===

==== Metadata attribute values

The dbStr-2.map.data file contains metadata attribute values that consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | [yellow-background]*Unknown (stream value data size)* +
See section: <<variable_size_integer,Variable size integer>>
| ... | ... | | Metadata attribute value name +
Contains an UTF-8 encoded string with an end-of-string character
|===

==== Index values

The dbStr-3.map.data, dbStr-4.map.data and dbStr-5.map.data files contains
metadata attribute values that consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | [yellow-background]*Unknown* +
See section: <<variable_size_integer,Variable size integer>>
| ... | ... | | Index data size +
Contains a variable size integer
| ... | ... | | Index array +
Contains an array of 32-bit integer values
|===

=== Database streams map buckets file (dbStr-#.map.buckets)

The database streams map buckets file (dbStr-#.map.buckets) file is variable of
size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 x number of entries | | Array of 32-bit offsets +
[yellow-background]*TODO:Relates to an index in the corresponding dbStr-#.map.offsets file?*
| ... | ... | 0 | [yellow-background]*Unknown (empty)*
|===

== Notes

....
/.Spotlight-V100/Store-V2/${STORE_UUID}/store.updates
/.Spotlight-V100/Store-V2/${STORE_UUID}/store_generation
....

:numbered!:
[appendix]
== References

`[REFERENCE]`

[cols="1,5",options="header"]
|===
| Title: | Common Metadata Attribute Keys
| Author(s): | Apple Inc.
| URL: | https://developer.apple.com/documentation/coreservices/file_metadata/mditem/common_metadata_attribute_keys
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

