= BSM event auditing file format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | BSM event auditing file format
| Classification: | Public
| Keywords: | BSM, OpenBSM
|===

[preface]
== License
....
Copyright (C) 2016-2018, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | December 2016 | Initial version.
| 0.0.2 | J.B. Metz | June 2018 | Additional changes.
|===

:numbered:
== Overview
[yellow-background]*TODO: complete documentation*

* One or more audit events
  * Header token type (AUT_HEADER32, AUT_HEADER32_EX, AUT_HEADER64, AUT_HEADER64_EX)
  * (AUT_TEXT, AUT_PATH, AUT_RETURN32)
  * (AUT_SUBJECT32, AUT_TEXT, AUT_RETURN32)
  * Trailer token type (AUT_TRAILER)

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | big-endian
| Date and time values |
| Character strings |
|===

=== Token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | Token data
|===

=== [[token_types]]Token types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00 | AUT_INVALID |
| | |
| 0x11 | AU_FILE_TOKEN +
AUT_OTHER_FILE +
AUT_OTHER_FILE32 | Control token type
| 0x12 | AUT_OHEADER | Control token type
| 0x13 | AU_HEADER_32_TOKEN +
AUT_TRAILER |
| 0x14 | AU_HEADER_32_TOKEN +
AUT_HEADER +
AUT_HEADER32 |
| 0x15 | AU_HEADER_EX_32_TOKEN +
AUT_HEADER32_EX |
| | |
| 0x21 | AU_DATA_TOKEN +
AU_ARB_TOKEN +
AUT_DATA |
| 0x22 | AU_IPC_TOKEN +
AUT_IPC |
| 0x23 | AU_PATH_TOKEN +
AUT_PATH |
| 0x24 | AU_SUBJECT_32_TOKEN +
AUT_SUBJECT +
AUT_SUBJECT32 |
| 0x25 | AUT_XATPATH |
| 0x26 | AU_PROCESS_32_TOKEN +
AUT_PROCESS +
AUT_PROCESS32 |
| 0x27 | AU_RETURN_32_TOKEN +
AUT_RETURN +
AUT_RETURN32 |
| 0x28 | AU_TEXT_TOKEN +
AUT_TEXT |
| 0x29 | AU_OPAQUE_TOKEN +
AUT_OPAQUE |
| 0x2a | AU_IN_ADDR_TOKEN +
AUT_IN_ADDR |
| 0x2b | AU_IP_TOKEN +
AUT_IP |
| 0x2c | AU_IPORT_TOKEN +
AUT_IPORT |
| 0x2d | AU_ARG32_TOKEN +
AUT_ARG +
AUT_ARG32 |
| 0x2e | AU_SOCK_TOKEN +
AUT_SOCKET |
| 0x2f | AU_SEQ_TOKEN +
AUT_SEQ |
| 0x30 | AUT_ACL | Modifier token type
| 0x31 | AUT_ATTR |
| 0x32 | AUT_IPC_PERM |
| 0x33 | AUT_LABEL | Modifier token type
| 0x34 | AUT_GROUPS | Modifier token type
| 0x35 | AUT_ILABEL +
AUT_ACE | Modifier token type
| 0x36 | AUT_SLABEL | Modifier token type
| | |
| 0x38 | AUT_PRIV | Modifier token type
| 0x39 | AUT_UPRIV | Modifier token type
| 0x3a | AUT_LIAISON | Modifier token type
| 0x3b | AUT_NEWGROUPS |
| 0x3c | AUT_EXEC_ARGS |
| 0x3d | AUT_EXEC_ENV |
| 0x3e | AUT_ATTR32 |
| 0x3f | AUT_UNAUTH |
| 0x40 | AUT_XATOM |
| 0x41 | AUT_XOBJ |
| 0x42 | AUT_XPROTO |
| 0x43 | AUT_XSELECT |
| 0x44 | AUT_XCOLORMAP |
| 0x45 | AUT_XCURSOR |
| 0x46 | AUT_XFONT |
| 0x47 | AUT_XGC |
| 0x48 | AUT_XPIXMAP |
| 0x49 | AUT_XPROPERTY |
| 0x4a | AUT_XWINDOW |
| 0x4b | AUT_XCLIENT |
| | |
| 0x51 | AUT_CMD |
| 0x52 | AUT_EXIT |
| | |
| 0x60 | AUT_ZONENAME |
| | |
| 0x70 | AUT_HOST |
| 0x71 | AUT_ARG64 |
| 0x72 | AUT_RETURN64 |
| 0x73 | AUT_ATTR64 |
| 0x74 | AUT_HEADER64 |
| 0x75 | AUT_SUBJECT64 |
| | |
| 0x77 | AUT_PROCESS64 |
| 0x78 | AUT_OTHER_FILE64 |
| 0x79 | AUT_HEADER64_EX |
| 0x7a | AUT_SUBJECT32_EX |
| 0x7b | AUT_PROCESS32_EX |
| 0x7c | AUT_SUBJECT64_EX |
| 0x7d | AUT_PROCESS64_EX |
| 0x7e | AUT_IN_ADDR_EX |
| 0x7f | AUT_SOCKET_EX |
3+| _Not defined by BSM_
| 0x80 | AU_SOCK_INET_32_TOKEN +
AUT_SOCKINET32 |
| 0x81 | AU_SOCK_INET_128_TOKEN +
AUT_SOCKINET128 |
| 0x82 | AU_SOCK_UNIX_TOKEN +
AUT_SOCKUNIX |
|===

....
/*
 * Data token types
#define AUT_SERVER              ((char)0x25)
#define AUT_SERVER32            AUT_SERVER
 */

/*
 * Modifier token types

#define AUT_CLEAR               ((char)0x37)
#define AUT_PRIV                ((char)0x38)
#define AUT_UPRIV               ((char)0x39)
#define AUT_LIAISON             ((char)0x3A)
 
 */

#define AU_ATTR_TOKEN               0x31
#define AU_IPCPERM_TOKEN            0x32
#define AU_NEWGROUPS_TOKEN          0x3B
#define AU_EXEC_ARG_TOKEN           0x3C
#define AU_EXEC_ENV_TOKEN           0x3D
#define AU_ATTR32_TOKEN             0x3E

/*
 * Command token types
 */
 
#define AU_CMD_TOKEN                0x51
#define AU_EXIT_TOKEN               0x52

/*
 * Miscellaneous token types

#define AUT_HOST                ((char)0x70)

 */

/*
 * 64bit token types

#define AUT_SERVER64            ((char)0x76)
#define AUT_OTHER_FILE64		((char)0x78)

 */

#define AU_ARG64_TOKEN              0x71
#define AU_RETURN_64_TOKEN          0x72
#define AU_ATTR64_TOKEN             0x73
#define AU_HEADER_64_TOKEN          0x74
#define AU_SUBJECT_64_TOKEN         0x75
#define AU_PROCESS_64_TOKEN         0x77

/*
 * Extended network address token types
 */
 
#define AU_HEADER_EX_64_TOKEN       0x79
#define AU_SUBJECT_32_EX_TOKEN      0x7a	
#define AU_PROCESS_32_EX_TOKEN      0x7b
#define AU_SUBJECT_64_EX_TOKEN      0x7c
#define AU_PROCESS_64_EX_TOKEN      0x7d
#define AU_IN_ADDR_EX_TOKEN	    0x7e
#define AU_SOCK_EX32_TOKEN          0x7f
#define AU_SOCK_EX128_TOKEN         AUT_INVALID         /*XXX*/
#define AU_IP_EX_TOKEN              AUT_INVALID         /*XXX*/
....

=== AUT_OTHER_FILE32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x11 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Timestamp +
Contains a POSIX timestamp in seconds
| 5 | 4 | | Number of microseconds
| 9 | 2 | | Name size
| 11 | ... | | Name
|===

=== AUT_OHEADER token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x2d | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_TRAILER token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x13 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | 0xb105 | Signature
| 3 | 4 | | Record size +
Data size of the event record
|===

=== AUT_HEADER32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x14 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Record size +
Data size of the event record
| 5 | 1 | | Format version
| 6 | 2 | | Event type +
See section: <<event_types,Event types>>
| 8 | 2 | | Modifier
| 10 | 4 | | Timestamp +
Contains a POSIX timestamp in seconds
| 14 | 4 | | Number of microseconds
|===

=== AUT_HEADER32_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x15 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Size
| 5 | 1 | | Format version
| 6 | 2 | | Event type +
See section: <<event_types,Event types>>
| 8 | 2 | | Modifier
| 10 | 4 | | Net type
4+| _If net type == IPv4_
| 14 | 4 | | IPv4 address
4+| _If net type == IPv6_
| 14 | 8 | | IPv6 address upper 64-bit
| 22 | 8 | | IPv6 address lower 64-bit
4+| _Common_
| ... | 4 | | Timestamp +
Contains a POSIX timestamp in seconds
| ... | 4 | | Number of microseconds
|===

[NOTE]
Plaso bsm.py defines this as token type 0x74

=== AUT_DATA token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x21 | Token type +
See section: <<token_types,Token types>>
| 1 | 1 | | [yellow-background]*Unknown (How to print, data format)* +
See section: <<data_formats,Data formats>>
| 2 | 1 | | Element data type +
See section: <<data_types,Data types>>
| 3 | 1 | | Number of elements (data units)
|===

=== AUT_IPC token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x22 | Token type +
See section: <<token_types,Token types>>
| 1 | 1 | | IPC object type +
See section: <<ipc_object_types,IPC object types>>
| 2 | 4 | | IPC object identifier
|===

=== AUT_PATH token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x23 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Path size
| 3 | ... | | Path +
Contain a string with an end-of-string character
|===

=== AUT_SUBJECT32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x24 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID) +
Contains a signed integer, where -1 respresents [yellow-background]*TODO*
| 5 | 4 | | Effective user identifier (UID) +
Contains a signed integer
| 9 | 4 | | Effective group identifier (GID) +
Contains a signed integer
| 13 | 4 | | Real user identifier (UID) +
Contains a signed integer
| 17 | 4 | | Real group identifier (GID) +
Contains a signed integer
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 4 | | Terminal port
| 33 | 4 | | IPv4 address
|===

=== AUT_XATPATH token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x25 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_PROCESS32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x26 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID)
| 5 | 4 | | Effective user identifier (UID)
| 9 | 4 | | Effective group identifier (GID)
| 13 | 4 | | Real user identifier (UID)
| 17 | 4 | | Real group identifier (GID)
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 4 | | Terminal port
| 33 | 4 | | IPv4 address
|===

[NOTE]
Double check this structure seems to be a duplicate of AUT_SUBJECT32

=== AUT_RETURN32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x27 | Token type +
See section: <<token_types,Token types>>
| 1 | 1 | | [yellow-background]*Unknown (Status or exit code? BSM_ERRORS)*
| 2 | 4 | | Return value
|===

=== AUT_TEXT token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x28 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Text size
| 3 | ... | | Text +
Contain a string with an end-of-string character
|===

=== AUT_OPAQUE token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x29 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | [yellow-background]*Unknown (Text size)*
| 3 | ... | | [yellow-background]*Unknown (Text)*
|===

=== AUT_IN_ADDR token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x2a | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | IPv4 address
|===

=== AUT_IP token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x2b | Token type +
See section: <<token_types,Token types>>
| 1 | 12 | | [yellow-background]*Unknown (struct ip)*
| 13 | 4 | | Source IPv4 address
| 17 | 4 | | Destination IPv4 address
|===

....
struct ip {
	u_char	ip_v:4,			/* version */
		ip_hl:4;		/* header length */
	u_char	ip_tos;			/* type of service */
	short	ip_len;			/* total length */
	u_short	ip_id;			/* identification */
	short	ip_off;			/* fragment offset field */
#define	IP_DF 0x4000			/* dont fragment flag */
#define	IP_MF 0x2000			/* more fragments flag */
	u_char	ip_ttl;			/* time to live */
	u_char	ip_p;			/* protocol */
	u_short	ip_sum;			/* checksum */
	struct	in_addr ip_src,ip_dst;	/* source and dest address */
};
....

=== AUT_IPORT token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x2c | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Port number
|===

=== AUT_ARG32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x2d | Token type +
See section: <<token_types,Token types>>
| 1 | 1 | | Argument index
| 2 | 4 | | Argument name
| 6 | 2 | | Argument value size
| 8 | ... | | Argument value +
Contains a string with an end-of-string character
|===

=== AUT_SOCKET token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x2e | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_SEQ token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x2f | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | [yellow-background]*Unknown (Sequence number)*
|===

=== AUT_ACL token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x30 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_ATTR token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x31 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | File mode
| 5 | 4 | | User identifier (UID)
| 9 | 4 | | Group identifier (GID)
| 13 | 4 | | [yellow-background]*Unknown (File system identifier?)*
| 17 | 8 | | [yellow-background]*Unknown (File system node identifier?)*
| 25 | 4 | | [yellow-background]*Unknown (Device?)*
|===

=== AUT_IPC_PERM token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x32 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | User identifier (UID)
| 5 | 4 | | Group identifier (GID)
| 9 | 4 | | Creator user identifier (UID)
| 13 | 4 | | Creator group identifier (GID)
| 17 | 4 | | Access mode
| 21 | 4 | | yellow-background]*Unknown (Slot sequence number?)*
| 25 | 4 | | yellow-background]*Unknown (Key?)*
|===

=== AUT_LABEL token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x33 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_GROUPS token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x33 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | [yellow-background]*Unknown (Group number?)*
|===

=== AUT_ACE token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x35 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_PRIV token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x38 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_UPRIV token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x39 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_LIAISON token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x3a | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_NEWGROUPS token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x3b | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | [yellow-background]*Unknown (New group number?)*
|===

=== AUT_EXEC_ARGS token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x3c | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Number of arguments
| 5 | ... | | Array of argument strings +
Contains strings with an end-of-string character
|===

=== AUT_EXEC_ENV token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x3d | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Number of environment variables
| 5 | ... | | Array of environment variable strings +
Contains strings with an end-of-string character
|===

=== AUT_ATTR32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x3e | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | File mode
| 5 | 4 | | User identifier (UID)
| 9 | 4 | | Group identifier (GID)
| 13 | 4 | | [yellow-background]*Unknown (File system identifier?)*
| 17 | 8 | | [yellow-background]*Unknown (File system node identifier?)*
| 25 | 4 | | [yellow-background]*Unknown (Device?)*
|===

=== AUT_UNAUTH token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x3f | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XATOM token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x40 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XOBJ token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x41 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XPROTO token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x42 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XSELECT token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x43 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XCOLORMAP token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x44 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XCURSOR token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x45 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XFONT token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x46 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XGC token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x47 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XPIXMAP token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x48 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XPROPERTY token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x49 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XWINDOW token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x4a | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_XCLIENT token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x4b | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_CMD token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x51 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_EXIT token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x72 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | [yellow-background]*Unknown (Status or exit code? BSM_ERRORS)*
| 5 | 4 | | Return value
|===

=== AUT_ZONENAME token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x60 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Time zone name size
| 3 | ... | | Time zone name
|===

=== AUT_HOST token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x70 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_ARG64 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x71 | Token type +
See section: <<token_types,Token types>>
| 1 | 1 | | Argument index
| 2 | 8 | | Argument name
| 10 | 2 | | Argument value size
| 12 | ... | | Argument value +
Contains a string with an end-of-string character
|===

=== AUT_RETURN64 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x72 | Token type +
See section: <<token_types,Token types>>
| 1 | 1 | | [yellow-background]*Unknown (Status or exit code? BSM_ERRORS)*
| 2 | 8 | | Return value
|===

=== AUT_ATTR64 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x73 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | File mode
| 5 | 4 | | User identifier (UID)
| 9 | 4 | | Group identifier (GID)
| 13 | 4 | | [yellow-background]*Unknown (File system identifier?)*
| 17 | 8 | | [yellow-background]*Unknown (File system node identifier?)*
| 25 | 8 | | [yellow-background]*Unknown (Device?)*
|===

=== AUT_HEADER64 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x74 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Size
| 5 | 1 | | Format version
| 6 | 2 | | Event type +
See section: <<event_types,Event types>>
| 8 | 2 | | Modifier
| 10 | 8 | | Timestamp +
Contains a POSIX timestamp in seconds
| 18 | 8 | | Number of microseconds
|===

[NOTE]
Plaso bsm.py defines this as token type 0x15

=== AUT_SUBJECT64 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x75 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID)
| 5 | 4 | | Effective user identifier (UID)
| 9 | 4 | | Effective group identifier (GID)
| 13 | 4 | | Real user identifier (UID)
| 17 | 4 | | Real group identifier (GID)
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 8 | | Terminal port +
Or [yellow-background]*Terminal port and terminal type*
| 37 | 4 | | IPv4 address
|===

=== AUT_PROCESS64 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x77 | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID)
| 5 | 4 | | Effective user identifier (UID)
| 9 | 4 | | Effective group identifier (GID)
| 13 | 4 | | Real user identifier (UID)
| 17 | 4 | | Real group identifier (GID)
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 8 | | Terminal port
| 37 | 4 | | IPv4 address
|===

[NOTE]
Double check this structure seems to be a duplicate of AUT_SUBJECT64

=== AUT_OTHER_FILE64 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x78 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_HEADER64_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x79 | Token type +
See section: <<token_types,Token types>>
| 1 | ... | | [yellow-background]*Unknown*
|===

=== AUT_SUBJECT32_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x7a | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID)
| 5 | 4 | | Effective user identifier (UID)
| 9 | 4 | | Effective group identifier (GID)
| 13 | 4 | | Real user identifier (UID)
| 17 | 4 | | Real group identifier (GID)
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 4 | | Terminal port
| 33 | 4 | | Net type
4+| _If net type == IPv4_
| 37 | 4 | | IPv4 address
4+| _If net type == IPv6_
| 37 | 8 | | IPv6 address upper 64-bit
| 45 | 8 | | IPv6 address lower 64-bit
|===

=== AUT_PROCESS32_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x7b | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID)
| 5 | 4 | | Effective user identifier (UID)
| 9 | 4 | | Effective group identifier (GID)
| 13 | 4 | | Real user identifier (UID)
| 17 | 4 | | Real group identifier (GID)
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 4 | | Terminal port
| 33 | 4 | | Net type
4+| _If net type == IPv4_
| 37 | 4 | | IPv4 address
4+| _If net type == IPv6_
| 37 | 8 | | IPv6 address upper 64-bit
| 45 | 8 | | IPv6 address lower 64-bit
|===

[NOTE]
Double check this structure seems to be a duplicate of AUT_SUBJECT32_EX

=== AUT_SUBJECT64_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x7c | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID)
| 5 | 4 | | Effective user identifier (UID)
| 9 | 4 | | Effective group identifier (GID)
| 13 | 4 | | Real user identifier (UID)
| 17 | 4 | | Real group identifier (GID)
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 4 | | Terminal port
| 31 | 4 | | Terminal type
| 37 | 4 | | Net type
4+| _If net type == IPv4_
| 41 | 4 | | IPv4 address
4+| _If net type == IPv6_
| 41 | 8 | | IPv6 address upper 64-bit
| 49 | 8 | | IPv6 address lower 64-bit
|===

=== AUT_PROCESS64_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x7d | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Audit user identifier (UID)
| 5 | 4 | | Effective user identifier (UID)
| 9 | 4 | | Effective group identifier (GID)
| 13 | 4 | | Real user identifier (UID)
| 17 | 4 | | Real group identifier (GID)
| 21 | 4 | | Process identifier (PID)
| 25 | 4 | | Session identifier
| 29 | 8 | | Terminal port +
Or [yellow-background]*Terminal port and terminal type*
| 37 | 4 | | Net type
4+| _If net type == IPv4_
| 41 | 4 | | IPv4 address
4+| _If net type == IPv6_
| 41 | 8 | | IPv6 address upper 64-bit
| 49 | 8 | | IPv6 address lower 64-bit
|===

=== AUT_IN_ADDR_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x7e | Token type +
See section: <<token_types,Token types>>
| 1 | 4 | | Net type
| 5 | 8 | | IPv6 address upper 64-bit
| 13 | 8 | | IPv6 address lower 64-bit
|===

=== AUT_SOCKET_EX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x7f | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Socket domain
| 3 | 2 | | Socket type
4+| _If socket domain == 26_
| 5 | 2 | | IP type
| 7 | 2 | | Source port
| 9 | 8 | | Source IPv6 address upper 64-bit
| 17 | 8 | | Source IPv6 address lower 64-bit
| 25 | 2 | | Destination port
| 27 | 8 | | Destination IPv6 address upper 64-bit
| 35 | 8 | | Destination IPv6 address lower 64-bit
4+| _Else_
| 5 | 2 | | IP type
| 7 | 2 | | Source port
| 9 | 4 | | Source IPv4 address
| 13 | 2 | | Destination port
| 15 | 4 | | Destination IPv4 address
|===

[NOTE]
Check if socket domain is really the deciding factor and not IP type

=== AUT_SOCKINET32 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x80 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Net type
| 3 | 2 | | Port number
| 5 | 4 | | IPv4 address
|===

=== AUT_SOCKINET128 token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x81 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Net type
| 3 | 2 | | Port number
| 5 | 8 | | IPv6 address upper 64-bit
| 13 | 8 | | IPv6 address lower 64-bit
|===

=== AUT_SOCKUNIX token

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | 0x82 | Token type +
See section: <<token_types,Token types>>
| 1 | 2 | | Family
| 3 | ... | | Path +
Contains a string with an end-of-string character
|===

=== [[data_types]]Data types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | AUR_BYTE +
AUR_CHAR | Data type element is 1 byte in size
| 1 | AUR_SHORT | Data type element is 2 bytes in size
| 2 | AUR_INT +
AUR_INT32 | Data type element is 4 bytes in size
| 3 | AUR_LONG +
AUR_INT64 | Data type element is 8 bytes in size
|===

=== [[data_formats]]Data formats

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | AUP_BINARY | Data is formatted as binary
| 1 | AUP_OCTAL | Data is formatted as an octal integer
| 2 | AUP_DECIMAL | Data is formatted as a decimal integer
| 3 | AUP_HEX | Data is formatted as an hexadecimal integer
| 4 | AUP_STRING | Data is formatted as a string
|===

=== [[event_types]]Event types

....
/etc/security/audit_event
....

=== [[ipc_object_types]]IPC object types

=== Socket types

....
#define	BSM_SOCK_DGRAM		1
#define	BSM_SOCK_STREAM		2
#define	BSM_SOCK_RAW		4
#define	BSM_SOCK_RDM		5
#define	BSM_SOCK_SEQPACKET	6

#define	BSM_SOCK_UNKNOWN	500
....

:numbered!:
[appendix]
== References

`[OPENBSM]`

[cols="1,5",options="header"]
|===
| Title: | OpenBSM project
| URL: | https://github.com/openbsm/openbsm
|===

[cols="1,5",options="header"]
|===
| Title: | Apple BSM audit record
| URL: | https://opensource.apple.com/source/xnu/xnu-517.9.5/bsd/bsm/audit_record.h
|===

[cols="1,5",options="header"]
|===
| Title: | OpenBSM audit record
| URL: | http://web.mit.edu/freebsd/head/contrib/openbsm/sys/bsm/audit_internal.h +
http://web.mit.edu/freebsd/head/contrib/openbsm/sys/bsm/audit_record.h
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

