= The Windows Job file format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary
The Windows Job file format is used by the Task Scheduler subsystem of
Windows. This specification is based on available documentation and was
enhanced by analyzing test data.

This document is intended as a working document for the Windows Job file
format specification.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Windows Job file format
| Classification: | Public
| Keywords: | Job file, .job
|===

[preface]
== License
....
Copyright (C) 2016-2018, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | January 2016 | Initial version.
| 0.0.2 | J.B. Metz | July 2016 | Additional information.
| 0.0.3 | J.B. Metz | May 2017 | Textual changes.
| 0.0.4 | J.B. Metz | May 2018 | Textual changes.
|===

:numbered:
== Overview
The job file consists of:

* fixed size data section
* variable size data section

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values |
| Character strings |
|===

=== Fixed size data section
The fixed size data (FIXDLEN_DATA) section is 68 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Product version +
See section: <<product_versions,Product versions>>
| 2 | 2 | | Format version
| 4 | 16 | | Job identifier +
Contains a UUID stored in little-endian
| 20 | 2 | | Application name offset +
Offset to the start of the application name in the variable-length data section +
The offset is relative from the start of the file
| 22 | 2 | | Triggers offset +
Offset to the start of the <<variable_length_triggers,triggers>> in the variable-length data section +
The offset is relative from the start of the file
| 24 | 2 | | Error retry count
| 26 | 2 | | Error retry interval +
Contains a value in minutes
| 28 | 2 | | Idle deadline +
Contains a value in minutes
| 30 | 2 | | Idle wait +
Contains a value in minutes
| 32 | 4 | | Priority +
See section: <<priority,Priority>>
| 36 | 4 | | Maximum run time +
Contains a value in milliseconds
| 40 | 4 | | Exit code
| 44 | 4 | | Status +
See section: <<status,Status>>
| 48 | 4 | | Flags +
See section: <<flags,Flags>>
| 52 | 16 | | Last run time +
Contains a <<system_time,system time>> or 0 if not set. +
[yellow-background]*TODO: confirm this is local time.*
|===

==== [[system_time]]System time
The system time is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Year +
Contains a value ranging from 1601 to (including) 30827
| 2 | 2 | | Month +
Contains a value ranging from 1 to (including) 12, where 1 represents January
| 4 | 2 | | Weekday +
Contains a value ranging from 0 to (including) 6, where 0 represents Sunday
| 6 | 2 | | Day +
Contains a value ranging from 1 to (including) 31
| 8 | 2 | | Hours +
Contains a value ranging from 1 to (including) 23
| 10 | 2 | | Minutes +
Contains a value ranging from 0 to (including) 59
| 12 | 2 | | Seconds +
Contains a value ranging from 0 to (including) 59
| 14 | 2 | | Milliseconds +
Contains a value ranging from 0 to (including) 999
|===

==== [[product_versions]]Product versions

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0400 | | Windows NT 4.0
| 0x0500 | | Windows 2000
| 0x0501 | | Windows XP
| 0x0600 | | Windows Vista
| 0x0601 | | Windows 7
| 0x0602 | | Windows 8
| 0x0603 | | Windows 8.1
| 0x0a00 | | Windows 10
|===

[NOTE]
The values above are those defined by MS-TSCH, they are known to be an
approximation to the actual Windows product version, and should be considered
more of a Window API (WINAPI) compatibility version.

==== [[priority]]Priority

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000020 | NORMAL_PRIORITY_CLASS | Normal priority class; no special scheduling requirements.
| 0x00000040 | HIGH_PRIORITY_CLASS | High priority class; preempt the threads of normal or idle priority class processes
| 0x00000080 | IDLE_PRIORITY_CLASS | Idle priority class; run only when the machine is idle.
| 0x00000100 | REALTIME_PRIORITY_CLASS | Real-time priority class; preempt the threads of all other processes, including operating system processes performing important tasks.
|===

==== [[status]]Status

[cols="1,1,5",options="header"]
|===
| 0x00041300 | SCHED_S_TASK_READY | Task is not running but is scheduled to run at some time in the future.
| 0x00041301 | SCHED_S_TASK_RUNNING | Task is currently running.
| 0x00041305 | SCHED_S_TASK_NOT_SCHEDULED | The task is not running and has no valid triggers.
|===

==== [[flags]]Flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | TASK_FLAG_INTERACTIVE | The task can interact with the logged-on user
| 0x00000002 | TASK_FLAG_DELETE_WHEN_DONE | The task can be deleted when there are no more scheduled run times
| 0x00000004 | TASK_FLAG_DISABLED | The task is disabled
| | |
| 0x00000010 | TASK_FLAG_START_ONLY_IF_IDLE | The task begins only if the computer is not in use at the scheduled time
| 0x00000020 | TASK_FLAG_KILL_ON_IDLE_END | The task can be terminated if the computer makes an idle to non-idle transition while the task is running
| 0x00000040 | TASK_FLAG_DONT_START_IF_ON_BATTERIES | The task cannot start if its target computer is running on battery power
| 0x00000080 | TASK_FLAG_KILL_IF_GOING_ON_BATTERIES | The task can end, and the associated application quit if the task's target computer switches to battery power
| 0x00000100 | TASK_FLAG_RUN_ONLY_IF_DOCKED | [yellow-background]*Unused*
| 0x00000200 | TASK_FLAG_HIDDEN | The task is hidden
| 0x00000400 | TASK_FLAG_RUN_IF_CONNECTED_TO_INTERNET | [yellow-background]*Unused*
| 0x00000800 | TASK_FLAG_RESTART_ON_IDLE_RESUME | The task can start again if the computer makes a non-idle to idle transition before all the task's triggers elapse
| 0x00001000 | TASK_FLAG_SYSTEM_REQUIRED | The task can cause the system to resume, or awaken if the system is sleeping
| 0x00002000 | TASK_FLAG_RUN_ONLY_IF_LOGGED_ON | The task can only run if the user specified in the task is logged on interactively
| | |
| [yellow-background]*0x00800000* | | [yellow-background]*Unknown*
| | |
| [yellow-background]*0x01000000* | TASK_APPLICATION_NAME | The task has an application name defined
|===

=== Variable-length data section
The variable-length data section is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Running instance count
| 2 | ... | | Application name +
Contains a <<variable_length_unicode_string,Variable-length Unicode string>>
| ... | ... | | Parameters +
Contains a <<variable_length_unicode_string,Variable-length Unicode string>>
| ... | ... | | Working Directory +
Contains a <<variable_length_unicode_string,Variable-length Unicode string>>
| ... | ... | | Author +
Contains a <<variable_length_unicode_string,Variable-length Unicode string>>
| ... | ... | | Comment +
Contains a <<variable_length_unicode_string,Variable-length Unicode string>>
| ... | ... | | User Data +
Contains a <<variable_length_user_data,User data>>
| ... | ... | | Reserved Data +
Contains a <<variable_length_reserved_data,Reserved data>>
| ... | ... | | Triggers +
See section: <<variable_length_triggers,Triggers>>
4+| _Optional_
| ... | ... | | Job Signature
|===

==== [[variable_length_unicode_string]]Variable-length Unicode string
The variable-length Unicode string is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | String size +
Contains the number of characters including the end-of-string character
| 2 | ... | | String +
Contains a UTF-16 little-endian formatted string with end-of-string character
|===

==== [[variable_length_user_data]]User data
The user data is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Data size +
Contains the number of bytes or 0 if not set
| 2 | ... | | Data
|===

==== [[variable_length_reserved_data]]Reserved data
The reserved data (TASKRESERVED1) is 2 or 10 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | 0 or 8 | Data size +
Contains the number of bytes or 0 if not set
| 2 | 4 | | Start error +
Contains the HRESULT error from the most recent attempt to start the task.
| 6 | 4 | | Task flags +
According to `[MSDN]` the task flags are not used.
|===

==== [[variable_length_triggers]]Triggers
The triggers are variable of size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Number of triggers
| 2 | ... | | Array of triggers +
See section: <<variable_length_trigger,Trigger>
|===

===== [[variable_length_trigger]]Trigger
The trigger is 48 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | 48 | Trigger size +
Contains the number of bytes
| 2 | 2 | 0 | [yellow-background]*Unknown (reserved)*
4+| _Start date_
| 4 | 2 | | Start year +
Contains a value in the range of 1601 to 30827
| 6 | 2 | | Start month +
Contains a value in the range of 1 to 12
| 8 | 2 | | Start day of month +
Contains a value in the range of 1 to 31
4+| _End date_
| 10 | 2 | | End year +
Contains a value in the range of 1601 to 30827
| 12 | 2 | | End month +
Contains a value in the range of 1 to 12
| 14 | 2 | | End day of month +
Contains a value in the range of 1 to 31
4+| _Start time_
| 16 | 2 | | Start hours +
Contains a value in range 0 to 23
| 18 | 2 | | Start minutes +
Contains a value in range 0 to 59
4+|
| 20 | 4 | | Duration in minutes
| 24 | 4 | | Interval in minutes
| 28 | 4 | | Trigger flags +
See section: <<variable_length_trigger_flags,Trigger flags>>
| 32 | 4 | | Trigger type +
See section: <<variable_length_trigger_types,Trigger types>>
| 36 | 3 x 2 | | Trigger specific values
| 42 | 2 | 0 | [yellow-background]*Unknown (padding)*
| 44 | 2 x 2 | 0 | [yellow-background]*Unknown (reserved)*
|===

==== [[variable_length_trigger_flags]]Trigger flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | TASK_TRIGGER_FLAG_HAS_END_DATE | Set if the task can stop at some point in time.
| 0x00000002 | TASK_TRIGGER_FLAG_KILL_AT_DURATION_END | Set if the task can be stopped at the end of the repetition period.
| 0x00000004 | TASK_TRIGGER_FLAG_DISABLED | Set if the trigger is disabled
|===

==== [[variable_length_trigger_types]]Trigger types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | ONCE | Not used according `[MSDN]`
| 0x00000001 | DAILY | Daily
| 0x00000002 | WEEKLY | Day of the week
| 0x00000003 | MONTHLYDATE | Day of the month
| 0x00000004 | MONTHLYDOW | Monthly day of week
| 0x00000005 | EVENT_ON_IDLE | Not used according `[MSDN]`
| 0x00000006 | EVENT_AT_SYSTEMSTART | Not used according `[MSDN]`
| 0x00000007 | EVENT_AT_LOGON | Not used according `[MSDN]`
|===

[yellow-background]*TODO: describe trigger data*
....
https://msdn.microsoft.com/en-us/library/cc248291.aspx
....

==== [[variable_length_job_signature]]Variable-length job signature
The variable-length job signature (JOB_SIGNATURE_HEADER) is 68 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | 1 | Signature format version
| 2 | 2 | 1 | Minimum client version
| 4 | 64 | | Signature
|===

[yellow-background]*TODO: notes*
....
The signature is calculated as follows:
* The Security Identifier (SID) of the file owner, the uuidJob field of the
  FIXDLEN_DATA structure, and the null-terminated string value from Application
  Name in the variable-length data section is bytewise concatenated in a buffer.
* A 16-byte MD5 [RFC1321] hash of the buffer is calculated.
* A private key is obtained from the system to be used for the digital signature.
* The hash is signed using MD5, and the signed hash is placed in the 64 bytes
  after the JOB_SIGNATURE_HEADER.
....

:numbered!:
[appendix]
== References

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title: | MS-TSCH: Task Scheduler Service Remoting Protocol
| URL: | https://msdn.microsoft.com/en-us/library/cc248263.aspx
|===

[cols="1,5",options="header"]
|===
| Title: | .JOB File Format
| URL: | https://msdn.microsoft.com/en-us/library/cc248285.aspx
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

