= Mac OS background item bookmark data format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

The Mac OS background item bookmark data format is used by the
backgrounditems.btm file.

This document is intended as a working document for the Mac OS background item
bookmark data format specification.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | Mac OS background item bookmark data format specification
| Classification: | Public
| Keywords: | Background item, Bookmark
|===

[preface]
== License

....
Copyright (C) 2024, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | February 2024 | Initial version.
|===

:numbered:
== Overview

The Mac OS background item bookmark data format is used by the
backgrounditems.btm file.

[NOTE]
This document used Mac OS to refer to the Macintosh Operating System in general,
instead of specific versions like Mac OS X or macOS. Mac OS X is used to refer
to version of Mac OS 10.0 or later.

The bookmark data is stored in the values of property with the following keys:

....
/$objects
....

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | Little-endian
| Date and time values | Cocoa date and time in number of seconds since 2001-01-01 00:00:00 UTC
| Character strings | Unicode strings are stored in UTF-8.
|===

=== Test version

The following version of programs were used to test the information within
this document:

* macOS 10.13 (High Sierra)

== Bookmark data

The bookmark data consists of:

* header
* data area
* table of contents (TOC)

=== Bookmark header

The bookmark header is 48 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "alis" +
"book" | Signature
| 4 | 4 | | Size +
Contains the size of the bookmark including the size of the header
| 8 | 4 | | [yellow-background]*Unknown (Flags or format version?)*
| 12 | 4 | | Data area start offset
| 26 | 32 | 0 | [yellow-background]*Unknown (empty values)*
|===

=== Data area

The data area is variable in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Data area size
| 4 | ... | | Data records
|===

==== Data record

The data record is variable in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Data size
| 4 | 4 | | Data type
| 8 | ... | | Data
|===

==== [[data_types]]Data types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000101 | | String +
The data contains an UTF-8 encoded string without end-of-string character
| | |
| 0x00000201 | | Binary data
| | |
| 0x00000301 | | Integer 8-bit signed
| 0x00000302 | | Integer 16-bit signed
| 0x00000303 | | Integer 32-bit signed
| 0x00000304 | | Integer 64-bit signed
| 0x00000305 | | Floating point single precision (32-bit)
| 0x00000306 | | Floating point double precision (64-bit)
| | |
| 0x00000400 | | Cocoa date and time +
The data contains a big-endian floating point double precision (64-bit)
| | |
| 0x00000500 | | Boolean false +
The data record contains no additional data
| 0x00000501 | | Boolean true +
The data record contains no additional data
| | |
| 0x00000601 | | Array +
The data contains 32-bit offsets to the array elements +
The offsets are relative to the start of the data area
| | |
| 0x00000701 | | Dictionary +
The data contains 32-bit key-value pairs of the dictionary elements
| | |
| 0x00000801 | | UUID (128-bit)
| | |
| 0x00000901 | | URL +
The data contains an UTF-8 encoded string without end-of-string character
| 0x00000902 | | URL (relative) +
The data contains a 32-bit offset to base URL, a 32-bit offset to UTF-8 string
|===

===== Notes

....
potential NULL type 0x0a01
....

....
0x00000300 corresponds to CFNumberType and values to:

kCFNumberSInt8Type = 1
kCFNumberSInt16Type = 2
kCFNumberSInt32Type = 3
kCFNumberSInt64Type = 4
kCFNumberFloat32Type = 5
kCFNumberFloat64Type = 6
kCFNumberCharType = 7
kCFNumberShortType = 8
kCFNumberIntType = 9
kCFNumberLongType = 10
kCFNumberLongLongType = 11
kCFNumberFloatType = 12
kCFNumberDoubleType = 13
kCFNumberCFIndexType = 14
kCFNumberNSIntegerType = 15
kCFNumberCGFloatType = 16
....

=== Table of contents

The table of contents consists of:

* table of contents header
* metadata entry
* key entries

==== Table of contents header

The table of contents header is 8 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Entries data size
| 4 | 4 | 0xfffffffe | [yellow-background]*Unknown (signature or marker?)*
|===

==== Table of contents metadata entry

The table of contents metadata entry is 12 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | TOC identifier
| 4 | 4 | | Next TOC header offset or 0 if not set
| 8 | 4 | | Number of tagged value entries in this TOC
|===

==== Table of contents tagged value entry

The table of contents tagged value entry is 12 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Value tag +
See section: <<value_tags,Value tags>>
| 4 | 4 | | Value data record offset +
The offset is relative to the start of the data area
| 8 | 4 | 0 | [yellow-background]*Unknown (emtpy value)*
|===

==== [[value_tags]]Value tags

If the MSB of the value tag is set the remaining value (0x7fffffff) contains
the offset of the name of a custom value, otherwise the value tag is predefined.
Below is a list of known predefined value tags.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00001003 | | Target URL
| 0x00001004 | | Target path +
Contains an array of strings containing path segments +
The path is relative from the mount point
| 0x00001005 | | [yellow-background]*Unknown (chain of ancestor file system identifiers)* +
Contains an array of integers containing file system identifiers, where the last element is the parent of the target, the second last the grand parent, etc.
| | |
| 0x00001010 | | Target (or resource) property flags +
See section: <<property_flags,property flags>>
| | |
| 0x00001020 | | Target filename
| | |
| 0x00001030 | | Target file system identifier (FSID)
| | |
| 0x00001040 | | Target creation date and time
| | |
| 0x00001054 | | [yellow-background]*Unknown*
| 0x00001055 | | [yellow-background]*Unknown*
| 0x00001056 | | [yellow-background]*Unknown*
| | |
| 0x00001101 | | [yellow-background]*Unknown*
| 0x00001102 | | [yellow-background]*Unknown*
| | |
| 0x00002000 | | TOC path
| | |
| 0x00002002 | | Volume path
| | |
| 0x00002005 | | Volume URL
| | |
| 0x00002010 | | Volume name
| 0x00002011 | | Volume identifier (UUID)
| 0x00002012 | | Volume size
| 0x00002013 | | Volume creation date and time
| | |
| 0x00002020 | | Volume property flags +
See section: <<property_flags,property flags>>
| | |
| 0x00002030 | | Volume root flag +
True if the volume was the filesystem root
| | |
| 0x00002040 | | Volume bookmark +
Contains a TOC identifier for disk image
| | |
| 0x00002050 | | Volume mount point URL
| | |
| 0x00002070 | | [yellow-background]*Unknown*
| | |
| 0x0000c001 | | Containing folder index +
Contains an integer index of containing folder in target path array
| | |
| 0x0000c011 | | Creator username +
Name of user that created bookmark
| 0x0000c012 | | Creator user identifier (UID) +
UID of user that created bookmark
| | |
| 0x0000d001 | | File reference flag +
True if creating URL was a file reference URL
| | |
| 0x0000d010 | | Creation options
| | |
| 0x0000e003 | | URL length array
| | |
| 0x0000f017 | | Display name
| | |
| 0x0000f020 | | Icon data +
Contains icns data
| 0x0000f021 | | Icon image
| 0x0000f022 | | Type binding info +
Contains dnib data
| | |
| 0x0000f030 | | Bookmark creation date and time
| | |
| 0x0000f080 | | Sandbox RW extension
| 0x0000f081 | | Sandbox RO extension
|===

==== [[property_flags]]Property flags

The property flags are 24 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Flags
| 8 | 8 | | Valid flags bitmask
| 16 | 8 | 0 | [yellow-background]*Unknown (empty values)*
|===

===== Target (or resource) property flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000000000000001 | kCFURLResourceIsRegularFile | Is regular file
| 0x0000000000000002 | kCFURLResourceIsDirectory | Is directory
| 0x0000000000000004 | kCFURLResourceIsSymbolicLink | Is symbolic link
| 0x0000000000000008 | kCFURLResourceIsVolume | Is volume
| 0x0000000000000010 | kCFURLResourceIsPackage | Is package
| 0x0000000000000020 | kCFURLResourceIsSystemImmutable | Is system immutable
| 0x0000000000000040 | kCFURLResourceIsUserImmutable | Is user immutable
| 0x0000000000000080 | kCFURLResourceIsHidden | Is hidden
| 0x0000000000000100 | kCFURLResourceHasHiddenExtension | Has hidden extension
| 0x0000000000000200 | kCFURLResourceIsApplication | Is application
| 0x0000000000000400 | kCFURLResourceIsCompressed +
kCFURLResourceIsSystemCompressed | Is compressed
| 0x0000000000000800 | kCFURLCanSetHiddenExtension | Can set hidden extension
| 0x0000000000001000 | kCFURLResourceIsReadable | Is readable
| 0x0000000000002000 | kCFURLResourceIsWriteable | Is writeable
| 0x0000000000004000 | kCFURLResourceIsExecutable | Is executable
| 0x0000000000008000 | kCFURLIsAliasFile | Is alias file
| 0x0000000000010000 | kCFURLIsMountTrigger | Is mount trigger
|===

===== Volume property flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000000000000001 | kCFURLVolumeIsLocal | Is local volume
| 0x0000000000000002 | kCFURLVolumeIsAutomount | Is mounted by the auto-mounter
| 0x0000000000000004 | kCFURLVolumeDontBrowse | Is hidden from user browsing
| 0x0000000000000008 | kCFURLVolumeIsReadOnly | Is read-only
| 0x0000000000000010 | kCFURLVolumeIsQuarantined | Is mounted with quarantine bit
| 0x0000000000000020 | kCFURLVolumeIsEjectable | Is ejectable
| 0x0000000000000040 | kCFURLVolumeIsRemovable | Is removable
| 0x0000000000000080 | kCFURLVolumeIsInternal | Is internal
| 0x0000000000000100 | kCFURLVolumeIsExternal | Is exteranal
| 0x0000000000000200 | kCFURLVolumeIsDiskImage | Is disk image
| 0x0000000000000400 | kCFURLVolumeIsFileVault | Is FileVault encrypted
| 0x0000000000000800 | kCFURLVolumeIsLocaliDiskMirror | Is local iDisk mirror
| 0x0000000000001000 | kCFURLVolumeIsiPod | Is iPod
| 0x0000000000002000 | kCFURLVolumeIsiDisk | Is iDisk
| 0x0000000000004000 | kCFURLVolumeIsCD | Is CD
| 0x0000000000008000 | kCFURLVolumeIsDVD | Is DVD
| 0x0000000000010000 | kCFURLVolumeIsDeviceFileSystem | Is device file system
| 0x0000000000020000 | kCFURLVolumeIsTimeMachine | Is time machine
| 0x0000000000040000 | kCFURLVolumeIsAirport | Is Airport
| 0x0000000000080000 | kCFURLVolumeIsVideoDisk | Is video disk
| 0x0000000000100000 | kCFURLVolumeIsDVDVideo | Is video DVD
| 0x0000000000200000 | kCFURLVolumeIsBDVideo | Is video DB
| 0x0000000000400000 | kCFURLVolumeIsMobileTimeMachine | Is mobile time machine
| 0x0000000000800000 | kCFURLVolumeIsNetworkOptical | Is optical network
| 0x0000000001000000 | kCFURLVolumeIsBeingRepaired | Is being repaired
| 0x0000000002000000 | kCFURLVolumeIsBeingUnmounted | Is being unmounted
| | |
| 0x0000000100000000 | kCFURLVolumeSupportsPersistentIDs |
| 0x0000000200000000 | kCFURLVolumeSupportsSearchFS |
| 0x0000000400000000 | kCFURLVolumeSupportsExchange |
| | |
| 0x0000001000000000 | kCFURLVolumeSupportsSymbolicLinks |
| 0x0000002000000000 | kCFURLVolumeSupportsDenyModes |
| 0x0000004000000000 | kCFURLVolumeSupportsCopyFile |
| 0x0000008000000000 | kCFURLVolumeSupportsReadDirAttr |
| 0x0000010000000000 | kCFURLVolumeSupportsJournaling |
| 0x0000020000000000 | kCFURLVolumeSupportsRename |
| 0x0000040000000000 | kCFURLVolumeSupportsFastStatFS |
| 0x0000080000000000 | kCFURLVolumeSupportsCaseSensitiveNames |
| 0x0000100000000000 | kCFURLVolumeSupportsCasePreservedNames |
| 0x0000200000000000 | kCFURLVolumeSupportsFLock |
| 0x0000400000000000 | kCFURLVolumeHasNoRootDirectoryTimes |
| 0x0000800000000000 | kCFURLVolumeSupportsExtendedSecurity |
| 0x0001000000000000 | kCFURLVolumeSupports2TBFileSize |
| 0x0002000000000000 | kCFURLVolumeSupportsHardLinks |
| 0x0004000000000000 | kCFURLVolumeSupportsMandatoryByteRangeLocks |
| 0x0008000000000000 | kCFURLVolumeSupportsPathFromID |
| | |
| 0x0020000000000000 | kCFURLVolumeIsJournaling |
| 0x0040000000000000 | kCFURLVolumeSupportsSparseFiles |
| 0x0080000000000000 | kCFURLVolumeSupportsZeroRuns |
| 0x0100000000000000 | kCFURLVolumeSupportsVolumeSizes |
| 0x0200000000000000 | kCFURLVolumeSupportsRemoteEvents |
| 0x0400000000000000 | kCFURLVolumeSupportsHiddenFiles |
| 0x0800000000000000 | kCFURLVolumeSupportsDecmpFSCompression |
| 0x1000000000000000 | kCFURLVolumeHas64BitObjectIDs |
|===

:numbered!:
[appendix]
== References

[cols="1,5",options="header"]
|===
| Title: | CFURLPriv.h
| URL: | https://opensource.apple.com/source/CF/CF-1153.18/CFURLPriv.h.auto.html
|===

[cols="1,5",options="header"]
|===
| Title: | Mac Bookmark Format
| URL: | https://mac-alias.readthedocs.io/en/latest/bookmark_fmt.html
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

