= Windows Defender scan DetectionHistory file format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

The Windows Defender scan DetectionHistory file is used by the Windows Defender
Protection History. This specification is based on publicly available
documentation and was enhanced by analyzing test data.

This document is intended as a working document for the Windows Defender scan
DetectionHistory file format specification.


[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | Windows Defender scan DetectionHistory file format
| Classification: | Public
| Keywords: | Windows Defender
|===

[preface]
== License

....
Copyright (C) 2022, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | February 2022 | Initial version.
|===

:numbered:
== Overview

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values |
| Character strings | Unicode strings are stored in UTF-16 little-endian without the byte order mark (BOM).
|===

=== Header

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 8 | [yellow-background]*Unknown*
| 4 | 4 | 8 | [yellow-background]*Unknown*
| 8 | 8 | | [yellow-background]*Unknown*
|===

=== Value

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Data size
| 4 | 4 | | Data type
| 8 | ... | | Data
| ... | ... | | 64-bit alignment padding
|===

=== Data types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | | [yellow-background]*Unknown (NULL?)*
3+|
| 0x00000005 | | [yellow-background]*Unknown (32-bit integer?)*
| 0x00000006 | | [yellow-background]*Unknown (32-bit integer?)*
3+|
| 0x0000000a | | Filetime
3+|
| 0x00000015 | | Unicode string
3+|
| 0x0000001e | | GUID
3+|
| 0x00000028 | | [yellow-background]*Unknown (binary data?)*
|===

=== Known values

[cols="1,1,5",options="header"]
|===
| Index | Value | Description
| 0 | | Identifier +
Contains the GUID corresponding to the file name
| 1 | "Magic.Version:1.2" | [yellow-background]*Unknown (signature and version?)*
| 2 | | Name of the threat that was detected +
For example: "Virus:DOS/EICAR_Test_File"
| 3 | | [yellow-background]*Unknown* +
Seen: 0
| 4 | | [yellow-background]*Unknown* +
Seen: 5
| 5 | | Category +
See section: <<category,Category>>
| 6 | | [yellow-background]*Unknown* +
Seen: 0x6e
| 7 | | [yellow-background]*Unknown (Severity?)* +
Seen: 4
| 8 | | [yellow-background]*Unknown* +
Seen: 3
| 9 | | [yellow-background]*Unknown* +
Seen: 3
| 10 | | [yellow-background]*Unknown* +
Seen: 3
| 11 | | [yellow-background]*Unknown* +
Seen: 3
| 12 | | [yellow-background]*Unknown* +
Seen: 2
| 13 | | [yellow-background]*Unknown* +
Seen: 6
| 14 | | [yellow-background]*Unknown* +
Seen: 1
| 15 | "Magic.Version:1.2" | [yellow-background]*Unknown (signature and version?)*
| 16 | "file" | [yellow-background]*Unknown*
| 17 | | [yellow-background]*Unknown (path of file)*
| 18 | | [yellow-background]*Unknown* +
Seen: 0x10000001
| 19 | | [yellow-background]*Unknown (threat data size?)*
| 20 | | [yellow-background]*Unknown (threat data?)*
|===

=== [[category]]Category

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | INVALID |
| 1 | ADWARE |
| 2 | SPYWARE |
| 3 | PASSWORDSTEALER |
| 4 | TROJANDOWNLOADER |
| 5 | WORM |
| 6 | BACKDOOR |
| 7 | REMOTEACCESSTROJAN |
| 8 | TROJAN |
| 9 | EMAILFLOODER |
| 10 | KEYLOGGER |
| 11 | DIALER |
| 12 | MONITORINGSOFTWARE |
| 13 | BROWSERMODIFIER |
| 14 | COOKIE |
| 15 | BROWSERPLUGIN |
| 16 | AOLEXPLOIT |
| 17 | NUKER |
| 18 | SECURITYDISABLER |
| 19 | JOKEPROGRAM |
| 20 | HOSTILEACTIVEXCONTROL |
| 21 | SOFTWAREBUNDLER |
| 22 | STEALTHNOTIFIER |
| 23 | SETTINGSMODIFIER |
| 24 | TOOLBAR |
| 25 | REMOTECONTROLSOFTWARE |
| 26 | TROJANFTP |
| 27 | POTENTIALUNWANTEDSOFTWARE |
| 28 | ICQEXPLOIT |
| 29 | TROJANTELNET |
| 30 | FILESHARINGPROGRAM |
| 31 | MALWARE_CREATION_TOOL |
| 32 | REMOTE_CONTROL_SOFTWARE |
| 33 | TOOL |
| 34 | TROJAN_DENIALOFSERVICE |
| 36 | TROJAN_DROPPER |
| 37 | TROJAN_MASSMAILER |
| 38 | TROJAN_MONITORINGSOFTWARE |
| 39 | TROJAN_PROXYSERVER |
| 40 | VIRUS |
| 42 | KNOWN |
| 43 | UNKNOWN |
| 44 | SPP |
| 45 | BEHAVIOR |
| 46 | VULNERABILTIY |
| 47 | POLICY |
|===

=== Severity

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | | Unknown
| 1 | | Low
| 2 | | Moderate
| 3 | | High
| 4 | | Severe
|===

=== Status

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | | Unknown
| 1 | | Detected
| 2 | | Cleaned
| 3 | | Quarantined
| 4 | | Removed
| 5 | | Allowed
| 6 | | Blocked
|===

=== Type

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | | Known Bad
| 1 | | Behavior
| 2 | | Unknown
| 3 | | Known Good
| 4 | | NRI
|===

=== Threat data

....
0x00000000  01 00 00 00 14 00 00 00  f9 04 00 00 0d 05 00 00  ................
0x00000010  00 00 00 00 f9 04 00 00                           ........*...T.h.

Name:
0x00000010                           2a 00 00 00 54 00 68 00  ........*...T.h.
0x00000020  72 00 65 00 61 00 74 00  54 00 72 00 61 00 63 00  r.e.a.t.T.r.a.c.
0x00000030  6b 00 69 00 6e 00 67 00  53 00 68 00 61 00 32 00  k.i.n.g.S.h.a.2.
0x00000040  35 00 36 00 00 00                                 5.6...........1.

0x00000040                    06 00  00 00                    5.6...........1.

Value:
0x00000040                                 82 00 00 00 31 00  5.6...........1.
0x00000050  33 00 31 00 66 00 39 00  35 00 63 00 35 00 31 00  3.1.f.9.5.c.5.1.
0x00000060  63 00 63 00 38 00 31 00  39 00 34 00 36 00 35 00  c.c.8.1.9.4.6.5.
0x00000070  66 00 61 00 31 00 37 00  39 00 37 00 66 00 36 00  f.a.1.7.9.7.f.6.
0x00000080  63 00 63 00 61 00 63 00  66 00 39 00 64 00 34 00  c.c.a.c.f.9.d.4.
0x00000090  39 00 34 00 61 00 61 00  61 00 66 00 66 00 34 00  9.4.a.a.a.f.f.4.
0x000000a0  36 00 66 00 61 00 33 00  65 00 61 00 63 00 37 00  6.f.a.3.e.a.c.7.
0x000000b0  33 00 61 00 65 00 36 00  33 00 66 00 66 00 62 00  3.a.e.6.3.f.f.b.
0x000000c0  64 00 66 00 64 00 38 00  32 00 36 00 37 00 00 00  d.f.d.8.2.6.7...

0x000000d0  2a 00 00 00 54 00 68 00  72 00 65 00 61 00 74 00  *...T.h.r.e.a.t.
0x000000e0  54 00 72 00 61 00 63 00  6b 00 69 00 6e 00 67 00  T.r.a.c.k.i.n.g.
0x000000f0  53 00 69 00 67 00 53 00  65 00 71 00 00 00 04 00  S.i.g.S.e.q.....
0x00000100  00 00 b0 dd 2d dc 55 05  00 00 22 00 00 00 54 00  ....-.U..."...T.
0x00000110  68 00 72 00 65 00 61 00  74 00 54 00 72 00 61 00  h.r.e.a.t.T.r.a.
0x00000120  63 00 6b 00 69 00 6e 00  67 00 49 00 64 00 00 00  c.k.i.n.g.I.d...
0x00000130  06 00 00 00 4a 00 00 00  36 00 41 00 44 00 36 00  ....J...6.A.D.6.
0x00000140  31 00 36 00 42 00 37 00  2d 00 45 00 32 00 41 00  1.6.B.7.-.E.2.A.
0x00000150  41 00 2d 00 34 00 33 00  38 00 37 00 2d 00 41 00  A.-.4.3.8.7.-.A.
0x00000160  32 00 35 00 30 00 2d 00  37 00 38 00 33 00 38 00  2.5.0.-.7.8.3.8.
0x00000170  46 00 34 00 44 00 31 00  42 00 31 00 39 00 41 00  F.4.D.1.B.1.9.A.
0x00000180  00 00 30 00 00 00 54 00  68 00 72 00 65 00 61 00  ..0...T.h.r.e.a.
0x00000190  74 00 54 00 72 00 61 00  63 00 6b 00 69 00 6e 00  t.T.r.a.c.k.i.n.
0x000001a0  67 00 53 00 74 00 61 00  72 00 74 00 54 00 69 00  g.S.t.a.r.t.T.i.
0x000001b0  6d 00 65 00 00 00 04 00  00 00 e5 1b 5b 1f a7 20  m.e.........[.. 
0x000001c0  d8 01 32 00 00 00 54 00  68 00 72 00 65 00 61 00  ..2...T.h.r.e.a.
0x000001d0  74 00 54 00 72 00 61 00  63 00 6b 00 69 00 6e 00  t.T.r.a.c.k.i.n.
0x000001e0  67 00 54 00 68 00 72 00  65 00 61 00 74 00 4e 00  g.T.h.r.e.a.t.N.
0x000001f0  61 00 6d 00 65 00 00 00  06 00 00 00 34 00 00 00  a.m.e.......4...
0x00000200  56 00 69 00 72 00 75 00  73 00 3a 00 44 00 4f 00  V.i.r.u.s.:.D.O.
0x00000210  53 00 2f 00 45 00 49 00  43 00 41 00 52 00 5f 00  S./.E.I.C.A.R._.
0x00000220  54 00 65 00 73 00 74 00  5f 00 46 00 69 00 6c 00  T.e.s.t._.F.i.l.
0x00000230  65 00 00 00 26 00 00 00  54 00 68 00 72 00 65 00  e...&...T.h.r.e.
0x00000240  61 00 74 00 54 00 72 00  61 00 63 00 6b 00 69 00  a.t.T.r.a.c.k.i.
0x00000250  6e 00 67 00 53 00 68 00  61 00 31 00 00 00 06 00  n.g.S.h.a.1.....
0x00000260  00 00 52 00 00 00 63 00  66 00 38 00 62 00 64 00  ..R...c.f.8.b.d.
0x00000270  39 00 64 00 66 00 64 00  64 00 66 00 66 00 30 00  9.d.f.d.d.f.f.0.
0x00000280  30 00 37 00 66 00 37 00  35 00 61 00 64 00 66 00  0.7.f.7.5.a.d.f.
0x00000290  34 00 63 00 32 00 62 00  65 00 34 00 38 00 30 00  4.c.2.b.e.4.8.0.
0x000002a0  30 00 35 00 63 00 65 00  61 00 33 00 31 00 37 00  0.5.c.e.a.3.1.7.
0x000002b0  63 00 36 00 32 00 00 00  2a 00 00 00 54 00 68 00  c.6.2...*...T.h.
0x000002c0  72 00 65 00 61 00 74 00  54 00 72 00 61 00 63 00  r.e.a.t.T.r.a.c.
0x000002d0  6b 00 69 00 6e 00 67 00  53 00 69 00 67 00 53 00  k.i.n.g.S.i.g.S.
0x000002e0  68 00 61 00 00 00 06 00  00 00 52 00 00 00 37 00  h.a.......R...7.
0x000002f0  32 00 61 00 61 00 66 00  39 00 62 00 61 00 62 00  2.a.a.f.9.b.a.b.
0x00000300  39 00 34 00 38 00 32 00  36 00 64 00 39 00 63 00  9.4.8.2.6.d.9.c.
0x00000310  36 00 37 00 65 00 63 00  33 00 38 00 63 00 39 00  6.7.e.c.3.8.c.9.
0x00000320  30 00 64 00 65 00 37 00  64 00 62 00 38 00 32 00  0.d.e.7.d.b.8.2.
0x00000330  34 00 36 00 66 00 62 00  31 00 35 00 37 00 00 00  4.6.f.b.1.5.7...
0x00000340  26 00 00 00 54 00 68 00  72 00 65 00 61 00 74 00  &...T.h.r.e.a.t.
0x00000350  54 00 72 00 61 00 63 00  6b 00 69 00 6e 00 67 00  T.r.a.c.k.i.n.g.
0x00000360  53 00 69 00 7a 00 65 00  00 00 04 00 00 00 45 00  S.i.z.e.......E.
0x00000370  00 00 00 00 00 00 24 00  00 00 54 00 68 00 72 00  ......$...T.h.r.
0x00000380  65 00 61 00 74 00 54 00  72 00 61 00 63 00 6b 00  e.a.t.T.r.a.c.k.
0x00000390  69 00 6e 00 67 00 4d 00  44 00 35 00 00 00 06 00  i.n.g.M.D.5.....
0x000003a0  00 00 42 00 00 00 36 00  39 00 36 00 33 00 30 00  ..B...6.9.6.3.0.
0x000003b0  65 00 34 00 35 00 37 00  34 00 65 00 63 00 36 00  e.4.5.7.4.e.c.6.
0x000003c0  37 00 39 00 38 00 32 00  33 00 39 00 62 00 30 00  7.9.8.2.3.9.b.0.
0x000003d0  39 00 31 00 63 00 64 00  61 00 34 00 33 00 64 00  9.1.c.d.a.4.3.d.
0x000003e0  63 00 61 00 30 00 00 00  30 00 00 00 54 00 68 00  c.a.0...0...T.h.
0x000003f0  72 00 65 00 61 00 74 00  54 00 72 00 61 00 63 00  r.e.a.t.T.r.a.c.
0x00000400  6b 00 69 00 6e 00 67 00  53 00 63 00 61 00 6e 00  k.i.n.g.S.c.a.n.
0x00000410  46 00 6c 00 61 00 67 00  73 00 00 00 03 00 00 00  F.l.a.g.s.......
0x00000420  11 00 00 00 2e 00 00 00  54 00 68 00 72 00 65 00  ........T.h.r.e.
0x00000430  61 00 74 00 54 00 72 00  61 00 63 00 6b 00 69 00  a.t.T.r.a.c.k.i.
0x00000440  6e 00 67 00 49 00 73 00  45 00 73 00 75 00 53 00  n.g.I.s.E.s.u.S.
0x00000450  69 00 67 00 00 00 05 00  00 00 00 2e 00 00 00 54  i.g............T
0x00000460  00 68 00 72 00 65 00 61  00 74 00 54 00 72 00 61  .h.r.e.a.t.T.r.a
0x00000470  00 63 00 6b 00 69 00 6e  00 67 00 54 00 68 00 72  .c.k.i.n.g.T.h.r
0x00000480  00 65 00 61 00 74 00 49  00 64 00 00 00 03 00 00  .e.a.t.I.d......
0x00000490  00 1b 8a 00 80 32 00 00  00 54 00 68 00 72 00 65  .....2...T.h.r.e
0x000004a0  00 61 00 74 00 54 00 72  00 61 00 63 00 6b 00 69  .a.t.T.r.a.c.k.i
0x000004b0  00 6e 00 67 00 53 00 63  00 61 00 6e 00 53 00 6f  .n.g.S.c.a.n.S.o
0x000004c0  00 75 00 72 00 63 00 65  00 00 00 03 00 00 00 00  .u.r.c.e........
0x000004d0  00 00 00 2e 00 00 00 54  00 68 00 72 00 65 00 61  .......T.h.r.e.a
0x000004e0  00 74 00 54 00 72 00 61  00 63 00 6b 00 69 00 6e  .t.T.r.a.c.k.i.n
0x000004f0  00 67 00 53 00 63 00 61  00 6e 00 54 00 79 00 70  .g.S.c.a.n.T.y.p
0x00000500  00 65 00 00 00 03 00 00  00 00 00 00 00           .e...........
....

:numbered!:
[appendix]
== References

[cols="1,5",options="header"]
|===
| Title: | MSFT_MpThreat class
| URL: | https://docs.microsoft.com/en-us/previous-versions/windows/desktop/defender/msft-mpthreat
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

